### ISSUE TITLE
Acquire the dwyl.com domain

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#118]
At present when you type `dwyl.com` into your address bar and attempt to visit the site, you are _automatically_ re-directed to: http://www.desiringgod.org ... 

![desiring-god-home-page](https://cloud.githubusercontent.com/assets/194400/19649100/6865540a-99fc-11e6-9f3d-b86fb684ab7a.png)

clearly, they don't _need_ the domain.

We should formulate a letter to send to them asking them to transfer the domain to us in exchange for a donation (e.g: $500) which covers the historical cost they've had for _renting_ the domain from ICANN and promise to put a link to their site in our footer which will have way better SEO than the simple re-direct they have in place. 

according to http://allwhois.org/whois/dwyl.com the domain has `Creation Date: 2004-06-15T22:35:18Z` so they've had it for 12 years ... 

let's estimate (_generously_) they are spending $20 per year to keep the domain ... 
it's not _making_ them any sort of return so they should not be _averse_ to giving it to us if we make them an _offer_... 
## Todo:
- [ ] discuss/determine if we _want_ to invest the time to even _attempt_ to get the `.com` domain.
- [ ] formulate an offer including:
  - [ ] cash donation to their cause, handily they have a page for that: https://www.desiringgod.org/donate
  - [ ] Offer to keep a _permanent_ link in the footer of our site so they get perpetual SEO 
- [ ] update our website so that when we send them the offer we _look_ like a "_worthy_" org for them to consider transferring the domain to us ...
  - [ ] what charitable projects have we worked on?
  - [ ] how does our _mission_ align with theirs? 
  - [ ] why is a link from us good SEO? (_we need a blog https://github.com/dwyl/dwyl.github.io/issues/6 that raises our `pagerank`!!_)

**Comment by markwilliamfirth** [comment]
Dear Scott,

Many thanks for your reply. I'm writing to you in my capacity as a Director of DWYL LTD ("dwyl"). dwyl is a social enterprise formed of a worldwide network of web developers, working together to use technology to help others achieve their potential. The reason I wanted to write to you is in relation to the dwyl.com web domain. This web domain currently forwards to the Desiring God website at desiringgod.org. I'm writing to you to ask if you would be so kind as to transfer the domain for our social enterprise's use.

dwyl is the registered holder of the trademark, "DWYL" (trademark number: UK00003103535). Details of the trademark can be found below:

Trade mark: DWYL
Status: Registered
Filing date: 13 April 2015
Date of entry in register: 17 July 2015
Renewal date: 13 April 2025
Class: 9 Software
Name and Address details Owner(s) name: DWYL LTD, 14, Palmers Road, London, United Kingdom, E2 0SY
Country of Incorporation: United Kingdom
Company registration number: 09525434
First advert Journal : 2015/019
Date of publication : 08 May 2015

In addition to the above registered trademark, dwyl has a significant presence online. dwyl is in possession of the dwyl.io and dwyl.co web domains. dwyl also utilises the username @dwyl extensively across a number of websites and forums, including both Github (https://github.com/dwyl) and Twitter (https://twitter.com/dwyl).

We have been advised by several international intellectual property lawyers that due to our trademark and extensive online presence it is highly likely that if this case came to litigation we would have a very strong case to claim ownership of the domain. However, we do not wish to move to litigation as this might prove costly for both parties and we wanted to first see if we could first resolve the above issue with the owner of the domain.

Therefore we would like to offer Desiring God the opportunity to transfer to dwyl.com domain to dwyl. As a gesture of goodwill and as an appreciation of your cooperation in this matter, we would like to give you a donation of $250.00 to your organisation in return. This is a final and one-time offer that will expire in fourteen (14) days.

As technology consultants, we would be more than happy to assist in any way we can with the transfer process of the domain free of charge. Please inform us how you would like to proceed within the next fourteen (14) days. We are grateful for your help in this matter and look forward to hearing from you soon.

Yours sincerely,

Mark W. Firth
Director, dwyl

@iteles ok to send?

**Comment by nelsonic** [comment]
@markwilliamfirth I would _remove_ Trademark paragraph completely from the **_initial_ email** and appeal to Scott's good nature to "_do the right thing_" before mentioning our _legal_ claim.

Also, I would double the offer to $500 given that it's a _four-letter-dot-com-domain_...! 
(_if it was sold on the "open market" it would probably go for a **lot** more..._)
I wouldn't bother with the "final offer" sentence. 

`if` he _refuses_ our _first_ offer we should _focus_ our efforts on getting the US Trademark https://github.com/dwyl/hq/issues/228
in _addition_ to our UK trademark so that we can mention that 
we would "_**prefer not** to have to waste anyone's time with **ICANN Trademark Dispute**_" ...

We _could_ reword a bit to acknowledge that they are doing us a _favour_ in transferring the domain... emphasise how much it would _mean_ to us. 
Also, I would focus on the fact that we are an Open Source Learning Community and not a "For Profit" company ...
Can we propose the steps required and reassure him that it a painless process?

**Comment by markwilliamfirth** [comment]
@nelsonic they can't sell it on the open market - that would show the following:

>(i) circumstances indicating that you have registered or you have acquired the domain name primarily for the purpose of selling, renting, or otherwise transferring the domain name registration to the complainant who is the owner of the trademark or service mark or to a competitor of that complainant, for valuable consideration in excess of your documented out-of-pocket costs directly related to the domain name;

We were advised the US trademark is largely irrelevant in the case of the .com domain

Pretty sure we're a ltd (for profit) company?

**Comment by nelsonic** [comment]
Yeah, agree.
just sayin' if we _emphasise_ the community aspect of dwyl we can appeal to his "nice guy".

**Comment by markwilliamfirth** [comment]
Completed. $170. Currently forwarding to `dwyl.io` as interim solution.

[Kinda glad we didn't give them loads of money
](http://www.desiringgod.org/articles/do-you-trust-disney-with-your-kids)

**Comment by iteles** [comment]
😱

**Comment by nelsonic** [comment]
![celebrate](http://i.giphy.com/3o7abldj0b3rxrZUxW.gif)

**Comment by sohilpandya** [comment]
@markwilliamfirth THIS IS AWESOME!!!!

**Comment by sofer** [comment]
Wow. That is an impressive piece of business.

**Comment by nelsonic** [comment]
There haven't been any four-letter dot-com addresses available for a while ...
http://www.slate.com/blogs/future_tense/2013/12/04/four_letter_domain_names_zero_unclaimed_llll_dot_coms_left_on_the_internet.html
I think a _few_ people will be interested in the domain acquisition process ... Blog Post? 🤔
