### ISSUE TITLE
New (Lighter/Better-Battery-Life) MacBook for Ines

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#120]
## Why?

Given that Inês (_probably_) won't "_switch_" back to Microsoft Windows any time soon and the MacBookPro 13' Retina she is using is a bit on the "_Heavy_" side ... 
it's 3.48 pounds (_**1.58 kg** ... actually more like 1.7kg with the acrylic case_!) 
I _suggest_ Inês switches to the **MacBook '12 Retina** 2.03 pounds (**0.92 kg**) 
(_over **650g lighter** and has a lighter charger too!_)
The 12' MacBook is portability and battery-life focussed which is _exactly_ what Inês needs; not "_horsepower_" ... _we aren't doing "video editing" on our laptops so an i7 processor is pointless!_
## What?
- Video intro: https://youtu.be/hajnEpCq5SE
- Detail: http://www.apple.com/macbook/design/
- Reviews: 
  - Favourable http://www.theverge.com/2015/4/9/8372335/12-inch-macbook-review (_old model_)
  - "_Harsh but factual_" (_non-apple fanboy_): https://youtu.be/L2WOW8e2nZQ
- Oh, did I mention it's _Silent_. (no vents or fans!)
## How?

So, **2 weeks ago** when we went into town for lunch I "_speculatively_" bought a **2016 MacBook '12** at John Lewis for **£1049** (_in the knowledge that JohnLewis' 90day returns policy would mean if there were "better" laptops announced by Apple we could easily swap it_) with a ***3-year warrantee*** (_tip: buy **all** your Apple Gear from John Lewis cause you essentially get "free" Apple Care; they repair or give you a new one if your thing breaks!!_):

![retina-macbook-12-john-lewis-1049](https://cloud.githubusercontent.com/assets/194400/19804740/2834e3a0-9d08-11e6-99f0-747978d2d830.png)

As _predicted_, Apple have decided to "_adjust_" (_jack up_) their prices 
because the GBP<-->USD exchange rate has nose-dived _post-**brexit**_ ... so the _same_ MacBook now costs **_£1249_** on the Apple website:

![retina-macbook-1249-apple-store](https://cloud.githubusercontent.com/assets/194400/19804778/5fbcebd8-9d08-11e6-9709-4d64a7f81a67.png)

So my "_foolishness_" at "_not waiting_" for the new laptop to come out, meant that we _**saved £200**_ call it "_luck_" or "_risk-free hedging_" but the fact remains.

Means Inês' _current_ MacBookPro Retina '13 8GB RAM and 256GB Disk will be available for @sohilpandya to use until he _decides_ which of the _New_ MacBookPro's he's going to _burn_ his cash on... 😉 
## Tasks
- [x] backup Inês' settings & content from MBPR'13 to external drive
- [x] restore data & settings to MPR'12 
- [x] reset MBPR'13 to "factory" with OSX Sierra
- [x] enable Apple Watch Unlock on MPR'12 to avoid typing password see: https://9to5mac.com/2016/07/05/hands-on-auto-unlock-macos-sierra-beta-2-watchos-3-video/ (_optional/recommended_) 
- [x]  test the 4-port Hub we ordered https://www.amazon.co.uk/dp/B01H3K387Q to see if it's enough for Inês at the office. 

_Special thanks_ @Conorc1000 for making _all_ Apple Products _more expensive_ ... 😜  https://www.theguardian.com/technology/2016/oct/28/brexit-apple-mac-customers-prices-rise-us-dollar-pound-sterling

For anyone _interested_ in "value for money" and prepared to use a different OS (e.g. Ubuntu or Windows) the Dell XPS 13 https://youtu.be/t4jIxN5FNpg or Lenovo Thinkpad X1 Carbon https://youtu.be/eeZoG7wXjqM both have better _processors_ and more ports.

**Comment by sohilpandya** [comment]
@nelsonic I realised after our conversation last night that they had actually increased the price!!

**Comment by nelsonic** [comment]
@sohilpandya yep... `#ThanksBrexit`

**Comment by nelsonic** [comment]
Anyone else looking at the MacBook Pro 13" price thinking "ROFL" and considering alternatives ...
For £200 less than the MBP 13 2016 you get an HP Spectre 13" or 15" better spec in every dimension:
+ Comparison: https://www.youtube.com/watch?v=vNMrMoT5cb0
+ http://www.johnlewis.com/hp-spectre-x360-13-4129na-convertible-laptop-intel-core-i7-8gb-ram-512gb-ssd-13-3-touch-screen-ash-luxe-copper/p2857566 
+ Works with Ubuntu: http://askubuntu.com/questions/600528/is-ubuntu-compatible-with-the-hp-spectre-x360/601577
+ No "Dongles" to buy ... has HDMI and "normal" USB Ports (_as well as USB Type-C...!_) 

If you "_splash out_" £1299 on the 15" model: http://store.hp.com/UKStore/Merch/Product.aspx?id=T1D64EA&opt=ABU&sel=NTB you get a ***4k*** display, **16GB RAM**, **512GB SSD** and ***FULL Touch Screen***! almost makes Apple look like they are _joking_... 😉

**Comment by sohilpandya** [comment]
That's a great find but I'm not sure about it. Just worried because Its not a mac. Have you ever had that feeling?

I've got a question @iteles/@nelsonic, I can potentially get 17% off the MacBook. Question is can we claim VAT back on it as long as we get the receipt? Because that seems like a lot more "affordable" solution if I get 37% off the MacBook...

**Comment by iteles** [comment]
@sohilpandya dwyl is a VAT registered company so we have to claim VAT on our expenditure back. The question is whether the offer you're discussing also gives you a VAT receipt (in which case yes, this would be expected behaviour).

**Comment by iteles** [comment]
Couldn't set up the 'Unlock with Apple Watch' feature because I can't for the life of me remember the answer to one of the security questions I set up with my apple ID many years ago. Not too fussed. Will sort it out when I have some more time!

**Comment by sohilpandya** [comment]
@iteles that's a shame. I'd like to see that feature in action. ☺️

**Comment by nelsonic** [comment]
@sohilpandya you _should_ be able to set it up on the MBP'13 ... 🤔 
@iteles you can re-set your security questions when you're online. 💻 📶

**Comment by sohilpandya** [comment]
@nelsonic unfortunately it's too old for the unlock feature. 😢

**Comment by nelsonic** [comment]
@sohilpandya _really_...? wow! see how much it will go for on Ebay and we can use the proceeds towards getting a _newer_ one that will support 4k etc. 👍

**Comment by sohilpandya** [comment]
You could possibly get anywhere between £400 - £700, due to the condition and the dead pixel doesn't help either. 

It's not a big thing, it's in a perfectly usable condition and bound to last another ~2+ years. 

No point selling it IMO.

**Comment by nelsonic** [comment]
ping @iteles 🔔 
did you manage to setup apple watch unlock? 🤔

**Comment by markwilliamfirth** [comment]
@iteles

**Comment by iteles** [comment]
The process was simplified! No need for an apple ID and therefore all set up on the apple watch. Closing
