### ISSUE TITLE
New Joiner Welcome Pack ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#131]
This photo: www.linkedin.com/hp/update/6206405494173626368 got 16k< "likes" and 600< comments on LinkedIn 

![fanduel-employee-welcome-pack](https://cloud.githubusercontent.com/assets/194400/20658384/497b9c0e-b534-11e6-8476-3e193273d0ff.png)

Firstly, if this is _all_ it takes to get that much "social media engagement" ... wow! 🤔 

> Obviously **Fan Duel** - a "skills-based entertainment product" i.e. [**gambling website**!!](https://www.youtube.com/results?search_query=Daily+Fantasy+Sports%3A+Last+Week+Tonight) ... has money to _burn_ on "_nice things_" but I'm fairly certain other companies do similar things.
> I joined Groupon too early on for them to have a _formal_ "joiners process" so I had to put my own PC together and install my own OS etc. but there was something similar towards the end of my time there ... 

## Tasks/Todo

+ [ ] investigate what people _want_ and/or _need_ when they first start in an org/team
+ [ ] What is our list of things that will make people _feel loved_
  + [ ] Notebooks https://github.com/dwyl/print-me/issues/19
  + [ ] Other stationary ? @iteles thoughts?
  + [ ] Business Cards https://github.com/dwyl/print-me/issues/7
  + [ ] T-Shirt https://github.com/dwyl/print-me/issues/20 (_one or two?_)
  + [ ] Hoodie https://github.com/dwyl/print-me/issues/17
  + [ ] Headphones? (_noise cancelling. so people can get work done in noisy environments..._)
  + [ ] Laptop (_or BYOD_) 
  + [ ] Phone (_or BYOD_)

> relates to: https://github.com/dwyl/start-here/issues/106

**Comment by iteles** [comment]
I would also like to make sure that all of this is as sustainable as possible. 
Every developer has a pile of branded *swag* that they don't use, so the first step is to know what dwylers actually want and most importantly will *use* so that it doesn't end up in landfill.

So @dwyl/ateam, what would *you* use/need?

**Comment by Jbarget** [comment]
What I would use:
- Glass water bottle
- T-shirt
- Business Cards (would be nice to let the employee customise these somehow, colour? emoji? pattern? )
- Headphones
- Notebook
- Hoodie

Looking at that list all of them are in the 'nice to have' section as opposed to need.

**Comment by vdeturckheim** [comment]
The small thing that can make a difference: a short letter from someone who will be your manager (or at least help you on your first days/weeks) with an intro and a strong welcome. Meaning, "you already have a friend here."

**Comment by stevepeak** [comment]
I would love to learn what your team chooses here. [Codecov](https://codecov.io) would like to offer similar welcome packages to employees and customers. @nelsonic 😉

**Comment by iteles** [comment]
@stevepeak :laughing: Very subtle!

**Comment by harrygfox** [comment]
- usb charging cables (multiple ends? micro usb, iphone etc) - _little essentials (that I often seem to burn through)_
- [timer for breaks, pomodoros, huddles, standups etc](https://www.amazon.co.uk/Atdoshop-Tomatoes-minutes-mechanical-Kitchen/dp/B00S0W2ZNU/ref=sr_1_2?s=kitchen&ie=UTF8&qid=1484912103&sr=1-2&keywords=pomodoro)

**Comment by SimonLab** [comment]
- a red hoodie
- haskell,  elixir,  phoenix,  elm... functional stuff books
- a second **red** hoodie

**Comment by carolrmc** [comment]
Vladimir de Turckheim has the right idea here, but it doesn't need to be a
manager. A contact person who can welcome them tbefore they start and be a
'buddy' once they're at Palmer Street.

**Comment by markwilliamfirth** [comment]
I think the most important thing isn't the merchandise etc but the employee's new manager having an onboarding plan for the new employee. It doesn't set a good starting tone when a new employee starts and the new manager is ill-prepared or doesn't have a plan for the first week.

It's all about making the new starter **feel** like they are in safe hands and they are going to have the correct onboarding, support they need and learning opportunities to give them the best possible start in their role. The job of the manager is to remove any potential obstacles therefore allowing the new starter to hit the ground running.

**Comment by nelsonic** [comment]
@markwilliamfirth totally _agree_! how people _feel_ is _way_ more important than any swag ...
did you see: https://github.com/dwyl/start-here/issues/106 we need an _amazing_ "_onboarding_" process. 🦄 🌈 😂 ❤️ ✅ 🎉

**Comment by nelsonic** [comment]
@SimonLab please _list_ all the books we need to order and we will get them ordered today. thanks!

**Comment by iteles** [comment]
@markwilliamfirth That's definitely a given before we move onto this!

**Comment by SimonLab** [comment]
@nelsonic I have a few books in mind but I think you might already have them so could we instead have a library system where dwyl people could see which books are available (or recommended or interesting read) to borrow instead? If the books are already borrowed we can then buy more copies?

**Comment by nelsonic** [comment]
@SimonLab yes!! 😍

**Comment by katpas** [comment]
@nelsonic @iteles @markwilliamfirth if only there was a tool in prototype form aiming to help you handle that process 😁

**Comment by sohilpandya** [comment]
❤️ the idea of glass water bottle, notebook, T-shirts & hoodie! 😉

**Comment by stevepeak** [comment]
@iteles just for you 👍 😃 hehe

1. Branded Macbook lint cloth for the keyboard :neckbeard:
2. USB-C to USB (I just got one from Readme.io in the mail, pretty cool!) 🔌 
3. A stuffed animal that doubled as a screen cleaner 🐒
4. Branded  [The Tile App](https://www.thetileapp.com/en-us/corporate-promotions) 🔲

**Comment by Jbarget** [comment]
http://uk.keepcup.com/design-your-own/design-your-own-brew.html#Plug=white&Lid=white&Band=white&Cup=white&size=m

This could be great on so many levels:
- great gift
- people only have one coffee/tea vessel (less washing up)
- could make people wash up their own mug as they have _ownership_ of a lovely mug
- less mess from loads of used mugs
- less energy spent on washing up

**Comment by otajor** [comment]
@Jbarget 
> could make people wash up their own mug as they have _ownership_ of a lovely mug

V. euphemistic 😄 
Did you mean: "Everyone will know if you leave your mug unwashed in the sink"?

**Comment by Jbarget** [comment]
haha that didnt cross my mind but thats true as well :)

**Comment by nelsonic** [comment]
@Jbarget / @otajor that would _only_ work if we didn't have _any_ "_guest_" mugs ... i.e. un-named.
but I like the idea of giving people personalised mugs either way. 👍

**Comment by iteles** [comment]
@Jbarget I totally own a keepcup and use it all the time :heart:
