### ISSUE TITLE
FY16/17 company accounts

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#229]
We need to pull together the accounts for FY16/17 so far (ending March 2017), which includes:

+ [x] Understanding the best way to deal with our accounting #132 
+ [ ] Understanding R&D tax relief https://github.com/dwyl/hq/issues/112
+ [x] Understanding how best to take care of our expenses https://github.com/dwyl/hq/issues/191
+ [x] Determining when to set up PAYE #239 
+ [x] Paying @iteles and @nelsonic for FY16/17 as no money has been drawn for this year yet #240 
+ [x] Understanding of loan company accepted from ines and nelson
- [x] Inês to forward TC invoices to Mark
- [x] Inês to forward dates of ebay purchases to Mark
- [x] Inês to forward personal amazon expenses to Mark
- [x] Inês to send Mark miscellaneous expenses e.g. flight expenses etc
- [x] Inês to send Mark zipcar expenses
- [x] Inês to put developer invoices in drive folder and send link to Mark
  + **From @iteles: Done only until the end of July 2016 so far. It's best to pull these from the bank account rather than from the invoices as downloading these invoices from email and uploading to a folder is much more prone to human error and much slower than downloading the bank statement! Guaranteed: I have never made a payment without an invoice from the developer and 'we' (a VA) can match these to the payments from the account later rather than the other way around**

+ [x] Mark to reconcile bank
  + [x] Mark to check bank statement for developer invoice amounts
  + [x] Mark to pull Github charges from bank statement
  + [x] Mark to check Tableflip and Ice Cream Rocket Ship VAT amounts
+ [x] Mark to get FAC invoices from fac xero Accounts > Sales > Filter by DWYL LTD
+ [x] Mark to pull Google Apps for Work invoices from Google Admin console

- [x] Inês to update F&C sheet for missing old payments
- [ ] Mark to reconcile revenue tab against F&C sheet and bank
- [ ] Mark to check finance email for feb and mar expenses

- [x] Inês to send Mark csv of all coop transactions
  - [x] Mark to get Google, Github and F&C info from coop

Adding this as one of our highest priorities so that we can project spending and investment for 2017.

**Comment by markwilliamfirth** [comment]
Final two relate to

https://github.com/dwyl/finance/issues/2
https://github.com/dwyl/finance/issues/1

**Comment by iteles** [comment]
How do I get all of the developer invoices to you for 16/17? Folder on google drive? This may take me a while ... *sigh*

**Comment by markwilliamfirth** [comment]
Yeah - drive folder should be fine

**Comment by iteles** [comment]
@markwilliamfirth Can you get all of the google apps for work invoices out of the admin console?

**Comment by iteles** [comment]
@markwilliamfirth I'm not sure what you mean by this:
<img width="315" alt="screen shot 2017-03-22 at 21 25 17" src="https://cloud.githubusercontent.com/assets/4185328/24221401/1a092164-0f46-11e7-85c8-4abd427052b2.png">

**Comment by markwilliamfirth** [comment]
@iteles the fac spreadsheet has missing x's in some cells for old payments etc

**Comment by iteles** [comment]
Cool, I'll look into it tomorrow. There were two invoices we agreed were incorrect and i need to update the spreadsheet!

**Comment by iteles** [comment]
@markwilliamfirth Checked and the only 3 outstanding invoices are 1 that was raised erroneously (INV-00170) and the other 2 have open questions against them - we won't have those resolved until next financial year (F&C may have to raise new invoices there anyway or most likely, we'll make a donation to F&C international when it's set up) 👍

**Comment by markwilliamfirth** [comment]
@iteles please can you send me PDFs of the co-op account for 16/17?

**Comment by iteles** [comment]
@markwilliamfirth 👍  I've sent these to you before - could you please tell me which ones you're missing ? Is it just the last couple of months since our previous exchange?

**Comment by markwilliamfirth** [comment]
@iteles I was only sent 3 PDFs in March and a copy-pasted google doc of transactions. Please can you download the PDFs for 16/17?

**Comment by iteles** [comment]
Those 3 PDFs include all the transactions for the financial year up to March. I'll send the rest through tonight when reunited with my fob 👍

**Comment by iteles** [comment]
This was done in May.

**Comment by iteles** [comment]
@markwilliamfirth I think the tasks at the very top of this issue are now out of date?

The first task here is to review what we have and make an updated list of tasks required.
For FY15/16 these were handed in late so we need to get a solid start on this by the end of November.

**Comment by iteles** [comment]
Currently replying to a number of questions from accountants to finalise draft accounts.

**Comment by iteles** [comment]
Completed and submitted. Awaiting final paperwork from accountants before we close this.

**Comment by iteles** [comment]
Final paperwork received and stored in the appropriate G-drive folders.
