### ISSUE TITLE
Priorities for Ines & Nelson w.b. 27th March 

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#281]
## For reference:

**Ines:**
+ [x] Preparing for dwyl dinner #213 
+ [ ] Work with @markwilliamfirth  to answer questions and show people round https://github.com/dwyl/quietspace
+ [ ] Adding detail to dwyl's activities publicly #277 
+ [ ] Keep services projects ticking over
  + Complete OA stage 2 milestone https://github.com/OxfordAbstracts/application/issues/2588
  + Pair with @cleop on scrum mastering of https://github.com/research-resource/research_resource/ and https://github.com/pm5k/Freed_Website
  + IC demo https://github.com/InclusiveClassrooms/skills-wheel/issues/131
  + https://github.com/dwyl/time-apple-watch-app
+ [ ] Pipeline
  + [ ] Continue sales and staffing of LDMW #278 
  + [ ] Put together workshop proposal for CU #280
+ [ ] Continue speaking to lawyers about #178 

**Nelson:**
+ **Priority 1**: QA for OA stage 2 deadline https://github.com/OxfordAbstracts/application/issues/2588
+ https://github.com/dwyl/chat as part of https://github.com/healthlocker 
+ QA for https://github.com/healthlocker 
+ Directing work on #183 
+ QA of https://github.com/dwyl/tudo/issues/146
+ Liaising with @cleop on https://github.com/dwyl/learn-daydream-and-nightmare

**Comment by markwilliamfirth** [comment]
@iteles should this be closed now?

**Comment by nelsonic** [comment]
🎉
