### ISSUE TITLE
Hiring Process: New Joiner Offer Checklist

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#313]
One of @dwyl's ["USP"](https://www.entrepreneur.com/encyclopedia/unique-selling-proposition-usp)s is that we are `#HyperTransparent` and that _includes_ our Hiring Process! 😮 

We aren't the "_first_" company/organisation to make "_salaries_" `public`, 
see: http://www.huffingtonpost.co.uk/2016/03/06/transparent-salaries-public-buffer_n_9377452.html 
But I do think we are the first to make our **_Entire_ Hiring Process** `public`.

# What is `public` ?

+ The **checklist** of things we have to do for the person (_often referred to as "**candidate**" or "**joiner**"_). Generic sample checklist (_please add more_)!
  + [ ] Person approached us expressing an interest or we approached them
  + [ ] Person has required skills and experience for role applied for
  + [ ] Discussed at team meeting
  + [ ] Invited for remote interview
  + [ ] Coding assignment given
  + [ ] Coding assignment complete
  + [ ] In-person interview date scheduled (_if person is within travelling distance_) `else` 2nd Remote Interview.
  + [ ] Interview feedback collected (_this can be `public` provided we keep it generic and positive_) if the outcome is a "no" it's _crucial_ to be super-specific as to why. We will send this feedback to the candidate so capturing it in a `public` place is a _good_ thing for transparency of our process.
  + [ ] Formal Offer (_or "rejection" 😢  with link to feedback_) sent.
  + [ ] Start date agreed. 📆 
  + [ ] Ask the person to read and submit a PR to the "Handbook" to _confirm_ they read it.
  + [ ] Person starts working with @dwyl
  + [ ] Person lives & works happily ever after! 🎉 
+ Any discussion that does not include any personally identifiable information but is relevant to the hiring process. 
> e.g: I worked with `Bat Man` on `Project-X` and they were really good! They have my endorsement to join the team! 🦄  🎉 

# What _is_ (_Always_) Kept `private` ?

Details of the _person_ being hired:
+ Name of the person is **NOT** Mentioned on GitHub _both_ to protect the person's privacy and to prevent "_recruiters_" from _spamming_ the person while they are going through _our_ process.
+ Any other personally identifiable information like GitHub username, "Social Security" (National Insurance), email etc.
+ Names of any projects where they are a lead contributor and it would be _obvious_ who we are talking about.

### So how do we discuss a potential candidate in `public` if their info is `private`? 

Simple, we have a `"code name"` for each person which we _internally_ know but which is _totally meaningless_ to anyone "outside". Who doesn't _love_ a good code name? 😉 

## Code Name Generation

The person who _originally proposes_ the `new` candidate should also propose a `code name`.
The `code name` should be _totally unrelated_ to the person and using "_generic_" words like names of trees, animals (_flattering ones please_), or other random things from nature _or_ make up a super-hero name!! 💡 
Try to pick a two-word name so it can be _initialised_ e.g: `Rainbow Rocket` would be "RR".  
(_obviously avoid picking a pair of names that result in the initials of the person we are hiring!_)

## Long Term

_Eventually_ our Plan is to have a Hiring "_System_" that can _receive_ emails so we can keep track 
of who has applied and what "_stage_" they are in the "process".
This will be a _feature_ of our CRM which @iteles has notes on.
But in the _interim_ we can _still_ capture our checklists on GitHub.

**Comment by markwilliamfirth** [comment]
@nelsonic might make more sense to use a candidate ID as opposed to random words

>We aren't the "first" company/organisation to make "salaries" public

Our salaries aren't public?

**Comment by markwilliamfirth** [comment]
I'm not sure what benefit this provides to the public - it just shows a checklist of steps of an anonymous person going through the hiring process. It does little to provide insight, yet substantially increases administration. The hiring process can be described in a readme, the only additional information people are getting from this is how many people are in the pipeline and at what stage they're at? Is that worth the administration time?

**Comment by iteles** [comment]
We have to keep track of how far individuals are into the process anyway, so it would be great if you could detail the extra administration @markwilliamfirth for completeness 😊 
To me the biggest benefits are ensuring everyone knows that a) the people who have joined us have ticked every box and b) that everything we need to look at is in our single source of truth and we don't have to go hunting in another tool for the latest/can add the card to our github projects easily

**Comment by markwilliamfirth** [comment]
@iteles the administration would involve creating, updating and closing a number of checklists in several issues for candidates, as opposed to maintaining a single spreadsheet

It's also worth noting:
- We'll need to maintain a spreadsheet anyway, as this will include the personally identifiable information and comments, therefore we're doubling the workload
- As far as I understand people won't be notified with changes to checklist boxes - so it doesn't seem like people will be kept up to date unless they actively search and check the issues frequently
- The people who join us don't always follow the same process
  - Not everyone (such as myself) is a coder - should everyone be taking a coding test before joining?
- Making public how many people are applying for a role shows the candidate the available competition and their assessment of how necessary/urgent the role is vs the amount of competition could therefore allow them to artificially increase their salary in negotiations
- Making public how many people are in the process for the roles we are hiring for is commercially sensitive and may give a benefit to our competitors
- If several people stay in the recruitment process for extended periods or drop out of the recruitment process it may give signals to others to follow suit

**Comment by markwilliamfirth** [comment]
@iteles to update about hiring process transparency policy. Confirmation required around uploading status (not personal information) of all candidates currently in the pipeline

**Comment by markwilliamfirth** [comment]
@nelsonic I noticed you were interviewing but hadn't created an issue about it yet (I thought you wanted hiring transparent?) - can you confirm what position these candidates are applying for?

![1](https://user-images.githubusercontent.com/5732209/31990780-eeb7cfc4-b96d-11e7-82ba-da19ec7d11eb.png)
![2](https://user-images.githubusercontent.com/5732209/31990781-eed568fe-b96d-11e7-96a4-ce1fdb1ddedf.png)
![3](https://user-images.githubusercontent.com/5732209/31990782-eef5dbac-b96d-11e7-80cf-8e0f8901c372.png)

**Comment by iteles** [comment]
@markwilliamfirth Nelson was helping out one of our older clients who is interviewing for their internal team and asked Nelson to lend his expertise.

This isn't relevant to dwyl and our own hiring process.

**Comment by markwilliamfirth** [comment]
@iteles are you able to clarify how much time Nelson is spending on TC - on the calendar it seems quite a lot for something we're not being paid to do - this week alone is 6.2 hours
