### ISSUE TITLE
Comic Relief Grant with RASASC

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#412]
We're working on putting together a funding application with RASASC for the [Comic Relief Tech for Good 2018 grant](https://www.comicrelief.com/apply-for-grants/open-grants-initiatives/tech-for-good-2018), for a project beginning June 2018.

## Tasks
+ [x] Initial meeting to discuss project requirements
+ [x] Review application form with Ops Lead from RASASC and assign reposibilities
  + 2.5 Which areas of technology will your project cover?
  + 3.3 Ops Lead to send  RASASC budget, @iteles to fill in the rest
  + 5.1 This section is currently not letting us add partners - re-read guidance for funding initiative to determine why partners are N/A for this initiative: "Please
note that some questions in the form will be marked as not applicable as they are not relevant to your launch
initiative or proposal, and you are not required to complete these. Please ensure that you read the guidance for your
funding initiative carefully and be sure the answers you give clearly address the key points these questions are
seeking to draw out from your response."
+ [x] Email RASASC on initial impressions around pathways
+ [x] Review past winners
+ [x] Make bullet pointed list of what needs to be in the video (stages of the project, what the money will be used for)
+ [x] Send through budget and application form data
+ [x] Help with storyboarding video (@Cleop might need you for this!!)

### Deadline: 15th December 2017

**Comment by iteles** [comment]
Sent to RASASC:

2.5 This question is very very general. I would suggest the following apply:
<img width="522" alt="screen shot 2017-12-15 at 14 17 34" src="https://user-images.githubusercontent.com/4185328/34046253-524ebb8e-e1a4-11e7-857f-30f35be96940.png">

This application will _certainly_ work on desktop as well as mobile but "Desktop _publishing_" doesn't apply. I have added in 'Directory' because it is also a directory of resources as well as 'Sharing' because we can have a quick button that allows people to email themselves or a friend a particular resource, enabling sharing, but will leave it with you do determine whether these are appropriate.

3.3 Budget - The most appropriate template here appears to be 'CR Financial without partners' given that in 5.1 we've already ascertained it's not possible to add partners.
Having read into this further, Comic Relief determines "partners are defined as organisations who will be responsible for managing a share of the project budget" but in this case the _budget_ will be managed entirely by RASASC so this is not an issue.

Given how tight the £47,000 Comic Relief Grant can be when accounting for RASASC's £500 day rate for your own staff, I have attached a budget which includes a 40 - 45% discount on our standard rates to try to make this go further.

I have included 3 days of RASASC time over a 10 day discover period (mostly led by a user research/UX expert on our side) and 2 days of RASASC time per sprint (2 week period). Please let me know if you think this is not the correct amount and we'll adjust.

**Comment by iteles** [comment]
The longlist will come out in March 2018! Long wait on this one.

**Comment by iteles** [comment]
Sadly, this wasn't funded by Comic Relief, RASASC don't have any feedback from them as to why yet though. It will probably become more apparent when the shortlist comes out.
http://techforgoodhub.co.uk/

The videos of the grantees should also come out on Comic Relief's  youtube channel https://www.youtube.com/playlist?list=PL5KXCGEFbuhI8zgVSwm4qT82RY_qSP6HU

We should keep an eye out for funding opportunities for this though as it is a hugely beneficial projects and RASASC are very keen to work with us on it if they can find the funding.

cc @naazy @Cleop (as you were both involved)
