### ISSUE TITLE
VAT Return | November 2017 to end January 2018

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#415]
VAT return for the period of 01.11.2017 - 31.01.2018.

**Deadline:** 1st March 2018.

VAT return and payment deadline is 7th March but this task needs to be completed ahead of time so that we can ensure the correct funds are available in our outgoing account for this date..

Low priority whilst we are waiting for the period to finish, but will be revised in February.

## Tasks
+ [x] Make sure all expenses for the period are entered
+ [ ] Document the steps for this tasks ([what we currently have](https://github.com/dwyl/process-handbook/blob/master/finances.md#vat-return) is looking a bit abandoned)
+ [ ] Submit the VAT return

**Comment by iteles** [comment]
Currently entering my expenses for the period

**Comment by iteles** [comment]
Took 2 hours but done! Not a replicable process.

**Comment by rub1e** [comment]
This has been filed. 

It was an immensely painful process collecting all the receipts and invoices etc. and then matching them tp payments, but ultimately worthwhile 🤑 

In the future @iteles @nelsonic, could you get into the habit of

* always requesting a VAT invoice from Amazon or other online purchases (within the order details screen, there's a little menu on the top right where you can easily request invoices (sometimes they're already there)
![screenshot 2018-03-07 at 12 05 06](https://user-images.githubusercontent.com/11595920/37091384-de43af1e-21ff-11e8-810f-82f5944a6e65.png)

  * Credit notes or packing slips don't help - must have VAT on them 
* forwarding to me any email invoices you receive where the invoice is in the body of the email
* forwarding to the Xero files address any emails you receive with invoice attachments

**Comment by iteles** [comment]
@rub1e 👍  99% of the invoices I receive go to the finances email address so sit in your purview 😉

**Comment by rub1e** [comment]
(This issue was closed with an incomplete task because it's been migrated to #446)
