### ISSUE TITLE
Potential Client | TP Energy monitoring

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#417]
Based on our work at the SMG (thanks @SimonLab @Danwhy as well as @shouston3 and @Cleop!), we have been asked to submit a proposal for a piece of work developing the front end of an energy monitoring service.

Opening this issue to track work and progress

## Tasks
+ [x] Initial email exchange on brief
+ [x] Initial phone call
+ [x] Meeting with stakeholders (@iteles and @nelsonic attended)
+ [x] Send in credentials
+ [x] Send proposal
+ [x] Await feedback

**Comment by iteles** [comment]
😆 Yes! Thanks dwylbot!

**Comment by nelsonic** [comment]
@iteles what do you think of re-purposing _this_ image for the intro:
![image](https://user-images.githubusercontent.com/194400/33935295-4c0bd12e-dff3-11e7-9d12-5f804610b0ea.png)
Source: http://reneweconomy.com.au/what-the-tesla-powerwall-battery-means-for-households-61055

**Comment by nelsonic** [comment]
https://blog.kroy.io/monitoring-home-power-consumption-for-less-than-25/

**Comment by nelsonic** [comment]
@iteles _super_ keen to hear the _feedback_ from them ... ⏳ 😉

**Comment by iteles** [comment]
Indeed... They said they should have an answer by last Friday so I'm following up tomorrow 😊

**Comment by iteles** [comment]
Sadly, we didn't get this. 

+ It was apparently between us and one more contender (out of a group of 7)
+ They were supremely confident in our technical ability and that we would deliver on time and on budget
+ They praised our proposal as one of the best they've seen
+ They went with the other agency because they "needed something truly transformational" as this was the relaunch of a product and TP wanted to "go back to the market with something wildly different" and http://www.allofus.com/ has a design track record
  + They are a design agency who contract out development 
+ Apparently they were not very confident in their ability to deliver the technical side, but were enamoured with their portfolio of design work
+ They were very complimentary of us and we are confident we have a good relationship with them for any future work we might be able to help with

**Comment by nelsonic** [comment]
@iteles what can we do/learn to _avoid_ this in the future?

**Comment by nelsonic** [comment]
@iteles could you send them a follow up email to find out how the project went? 
Just out of _curiosity_ if they have shipped the product as we would like to _test_ it as _consumers_!
