### ISSUE TITLE
EPIC: Consolidate our GitHub "Workflow" into *Single* Reference

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#434]
## Situation / Intro

At present we have ***five*** GitHub repositories that contain "_bits_" of our "Workflow":

+ [https://github.com/dwyl/**contributing**](https://github.com/dwyl/contributing) - General guidance on contributing to a GitHub project
+ [https://github.com/dwyl/**process-handbook**](https://github.com/dwyl/process-handbook) - internal "processes" for dwyl projects at the time of writing it's only got _one_ image and is very [_text heavy_](https://github.com/dwyl/process-handbook/tree/53d2b71adb9ee3cac8c1f5ee3dd2d87dbfbfc26d) ...
+ [https://github.com/dwyl/**github-reference**](https://github.com/dwyl/github-reference) - GitHub for non-technical people ...
+ [https://github.com/dwyl/**product-owner-guide**](https://github.com/dwyl/product-owner-guide) - targeted at the Product Owner of the project
+ [https://github.com/dwyl/**labels**](https://github.com/dwyl/labels) - explains the purpose of and use-case for each of the labels.

Additionally we have [https://github.com/dwyl/**dwylbot**](https://github.com/dwyl/dwylbot) which _attempts_ to "guide" people 
to follow our "workflow" by posting helpful hint-messages in the issue(s) & pull requests.

_Unfortunately_, these repos are not _congruent_.

Furthermore they do not consider the use of [**GitHub Project Boards**](https://help.github.com/articles/about-project-boards/) for _visualising_ the progress of user stories through the "pipeline".
Allowing people to "***drag-and-drop***" issues from "Todo" to "In Progress" is _much_ better UX than **_manually_ applying** a `Label` and **_manually_ assigning** the issue to themself ... the act of dragging the issue to "In Progress" column should trigger "WorkflowBot" to perform both of these "admin" actions (add label & assign to user). 

## _Desirable_

It would be _preferable_ to have a **_single_ repository** that defines our _complete_ GitHub Workflow.

**Note**: I'm not _suggesting_ that the `product-owner-guide` is not _useful_ (_in fact I think that it's **really** good!_) just that it's not _tightly_ associated with the GH Workflow e.g:
![dwyl-product-owner-guide-glossary-backlog](https://user-images.githubusercontent.com/194400/36224802-8f0b63d2-11c0-11e8-9fc2-d9730abe8027.png)

> I _suggest_ we re-name the [https://github.com/dwyl/**contributing**](https://github.com/dwyl/contributing) to "***github-standard-workflow***" (_because including the word "**standard**" means that **nobody** can "argue" with it ... https://github.com/standard/standard ..._) 🙄 
And then _merge_ all the other _individual_ repositories into the newly renamed one as `.md` files within it.
We could even craft it into a "GitBook" the way "ThouhtBot" did with: [https://thoughtbot.com/playbook](https://user-images.githubusercontent.com/194400/36225088-7ba06512-11c1-11e8-8002-d65e6aeb2dfb.png)

## Todo

+ [ ] Collect _feedback_ from existing "_users_" of the dwyl GitHub Workflow (team members & clients)
  + [ ] Revise our _existing_ GitHub Workflow in response to feedback.
+ [ ] _Use_ **GitHub Project Boards** (_trello-like drag-and-drop_) so that _everyone_ on the project can see at a _glance_ what stories/tasks (issues) are being worked on and by _who_. (_there's a **reason** why Trello is so popular and tools like "ZenHub" and "Waffle.io" exist ... people **want** a visual "Board"_)
+ [ ] Determine which other columns we would like to Add to the standard GitHub Project Board (_the `default` columns are `Todo`, `In Progress` and `Done`_) > can we open a _separate_ issue for this?
  + [ ] "WorkflowBot" should automatically create the full array of Project Board columns when the app is added to the project using the API: https://developer.github.com/v3/projects/columns

### Sections to Include in the Revised Guide

The contents table should include:

+ [ ] Contributors - link to a _revised_ `CONTRIBUTING.md` that is _simplified_ for Open Source.
  + [ ] Separate guide 
and _detailed_ for "client work".
+ [ ] Stakeholders - anyone who has a vested interest in the success of the project but who may not be involved in _delivering_ the work.
+ [ ] Product Owner Guide - we can link to the (_revised_) `product-owner-guide`

## _Pain Point_

Given that we don't have a _single_ place we can point people to, 
I spent a _chunk_ of time _attempting_ to summarise the "Workflow" 
for one of our clients in a "single page" diagram:

<hr />
## Workflow Diagram

![tcm-workflow-with-blockers](https://user-images.githubusercontent.com/194400/31735912-26fa7892-b43b-11e7-9da1-75547a348f89.png)
<small>_**Click image** to view **large version**!_</small>
<small>_**Edit** this Google Doc: https://goo.gl/2UNVbw (using [draw.io](https://www.draw.io))_</small>

This workflow is optimised for our [**biggest constraint**](https://en.wikipedia.org/wiki/Theory_of_constraints): **_UI Developer_ Time**.

<hr />
> **Note**: I am not for a _moment_ suggesting this diagram is "perfect"! in fact I think it's "_meh_".
But it's just to illustrate that I had to create _several_ new columns in addition to the `default` ones that come with GitHub Project Boards and then _explain_ (_visually_) what each one is for.

## Questions:

+ [ ] Should we use GitHub Project Boards for our Open Source _modules_? or should we `limit` the use of the boards to the actual _Projects_? How much "_structure_" do Open Source modules need in their workflow? (_how much is "too much" which results in putting people **off* contributing...?_)
+ [ ] Should "WorkflowBot" be applicable to _all_ types of GitHub Repos or just "Apps" worked on by teams of (_paid_) developers. 

@Cleop / @iteles this is what I mentioned this morning in our _verbal_ discussion.
I've attempted to capture as much as possible in this issue to ensure that we cover _everything_ in the "Epic".

**Comment by nelsonic** [comment]
Not having a well-defined workflow is costing us time (_money_) 
as people "_don't know what to work on next_" 
or work on _low-priority_ (_low-benefit to end-users_) issues
and **don't _clearly_ communicate** with the rest of the team 
(_e.g: by "**dragging*** the story into the `In Progress` column ... 
multiple people work on the **same** story wastes **everyones** time!_)

Also, people still _insist_ on discussing user-stories in _ephemeral_ or _verbal_ "chat",
so issues do not contain the _full_ "context" or discussion. This ***destroys*** **_remote_-teamwork**. 
People _rarely_ use [_checklists_](http://atulgawande.com/book/the-checklist-manifesto), the _best_ way to track your _own_ progress (_and **communicate** with others_)
and ***nobody*** in `dwyl` has adapted to using ***GitHub Project Boards*** (Automated Kanban) ...
![image](https://user-images.githubusercontent.com/194400/36535481-b8bdcd3a-17c1-11e8-80f8-f6f4c2d682ad.png)

"Stakeholders" _love_ Trello. (_which is why Atlassian paid [$425 million](https://techcrunch.com/2017/01/09/atlassian-acquires-trello) for it last year ..._)
GitHub Projects gives us _many_ of the features of Trello _for free_!
_Specifically_ the ability to _see_ "at-a-glance" what is being worked on (_by who_)
and how "complete" it is ... if people `use` _checklists_ ... 🙄

**Comment by nelsonic** [comment]
No product owner or QA/lead wants to see a branch called "quick fix" ...
![branch-name-quickfix](https://user-images.githubusercontent.com/194400/48758002-80813100-ec96-11e8-9968-28690443c27e.png)

Instead, they want to see a _descriptive_ name and an issue number e.g: 
![image](https://user-images.githubusercontent.com/194400/48758040-a0b0f000-ec96-11e8-86dd-000136ae04d0.png)

"quick fix" is _exactly_ what its' name suggests, **_not_ a long-term solution** to the problem with maintainable code, documentation and tests. 😞

**Comment by iteles** [comment]
@nelsonic Thank you for opening this issue. I've been paying much closer attention to how/if these repos are used in the last few months since it was opened.

> I very much agree that this needs a serious revision and that our **entire workflow** needs to be in ***one place***.

The thing to consider here is that there are various _types_ of workflow included in these 6 repos.

### One resource: `github-standard-workflow`

This is by far a better name. 💪 

Our [Contributing Guide](https://github.com/dwyl/contributing) (extremely useful as a 'stand-alone' to add to our `contributing.md` files across OSS repos), [Definition of done](https://github.com/dwyl/definition-of-done), definitions within ['labels'](https://github.com/dwyl/labels) and everything in the [main readme of the 'Process Handbook'](https://github.com/dwyl/process-handbook) absolutely all belong in the same repo.

Within `github-standard-workflow`, I propose the following next steps:
+ [ ] Our [Contributing Guide](https://github.com/dwyl/**contributing**) remains as the _main `readme` so that it is still the first thing contributors to our OSS projects/packages/modules see
+ [ ] Introduction is updated to reflect this
+ [ ] Table of contents is added for remainder of documentation (definition of done, labels and scrum/development project processes)
+ [ ] All other `readme`s are added in a relevant folder structure within the repo for orderly access

### Other repos/parts of repos
+ Within ['Process Handbook'](https://github.com/dwyl/process-handbook), there are a lot of 'how to run a company' `md` files - these should be moved to the `hq` repo
+ The _code_ for [labels](https://github.com/dwyl/labels) should remain in the `labels` repo so that it can keep being evolved, with a reference to `github-standard-flow` for the label definitions
+ **Open questions**:
  + https://github.com/dwyl/product-owner-guide - I had originally envisioned this as a resource far beyond GitHub, as a reference for product owners in not just the technical/Github realm of their roles but also in being POs in general
     + As you say, it's hugely out of date, not tied tightly enough to our own processes and needs a firm revision
     + The vast majority of what is there _now_ is Github-flow specific so I don't see why it shouldn't be moved into `github-standard-workflow` and then if we choose to evolve it beyond that, we can break it out into its own repo again
  + https://github.com/dwyl/github-reference - This is an elementary Github resource which we found necessary when we first started working with clients (as a precursor of the basics before launching into the PO guide), but could very well be useful to beginner developers too
    + I suggest we a) Check to see whether there are any existing resources that are doing a better job of this for non-technical people and b) if not, update this issue and add it to `github-standard-workflow`

***@nelsonic Do you disagree with either of the first two points in the list above?***

If not, I'll move forward and get this done.

### On merging repos
There is really no way to port issues and their history from one repo to another. The only solution right now seems to be: https://github.com/IQAndreas/github-issues-import which creates threads posted by a bot like this:
https://github.com/IQAndreas-testprojects/github-issues-import-example/issues/10

The vast majority of the issues on https://github.com/dwyl/process-handbook are opened by myself and @rub1e so this isn't too much of an issue as we can use it as a backlog grooming session and re-open relevant issues only. https://github.com/dwyl/labels has quite a lot of issues opened by others however. We can keep these here if we decide to keep the code for `labels` separate to the labels definitions as proposed above.

<hr/>

Lastly, the `priority-1` update for me here is to include our usage of Github Projects and getting `dwylbot` to automate labels for us. We've been discussing it for a while and I feel it _every_ day when I'm the one updating labels because having to update the same thing in two places means no one does it.
