### ISSUE TITLE
Research & Development Tax relief

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#438]
The original issue for this was opened 14 October 2016 https://github.com/dwyl/hq/issues/112 but there is a huge amount of `noise` and unhelpful back and forth in there (which are available for reference if anyone is interested).

https://www.gov.uk/guidance/corporation-tax-research-and-development-rd-relief

### Context
We met with the consultants a three times over the last year, opting to deal with FY15/16 and FY16/17 simultaneously and determined the criteria necessary https://github.com/dwyl/hq/issues/112#issuecomment-346693484

## Tasks 
+ [x] Define criteria https://github.com/dwyl/hq/issues/112#issuecomment-346693484
+ [x] Receive, review, question and sign contracts with consultants
+ [x] Meet with consultants to agree projects which fall into this bracket
+ [x] Receive spreadsheet and info from consultants
+ [x] First pass of data for all projects, including estimated costs FY15/16
  + [x] Development costs
  + [x] Operations costs
+ [x] First pass of data for all projects, including estimated costs FY16/17
  + [x] Development costs
  + [x] Operations costs
+ [x] Review data
+ [x] Email spreadsheet to consultants for review
+ [x] Email accounts, tax computations and CT600 tax returns for FY15/16 & FY16/17
+ [x] Fill out projects spreadsheet
+ [x] Consultants to send draft of tax relief paperwork
+ [x] File for tax relief
+ [x] Receive decision on R&D tax relief
+ [x] Check & reconcile money received from HMRC against invoices from consultants

**Comment by iteles** [comment]
`priority-1` as this is @rub1e's top priority this week and my top priority once his portion is complete 😊

**Comment by rub1e** [comment]
Linked to #437

**Comment by rub1e** [comment]
To review: 

* I've now been through all the projects identified as having an R&D component and entered all the days worked by each *dwyler* into the Cost Collection Spreadsheet
* This took **much** longer than I'd planned for because the dwyl staff and contractors who had been paid to do our accounting had reconciled most of the invoices on Xero **without including** a *client reference* (or indeed uploading the invoices themselves)
  * Getting #437 done will solve this problem for the most part
* We'll still need an easy way to account for dwyl *employees'* time (currently captured in a separate spreadsheet) as well as *contractors'* time for 2017/18, perhaps this is something that Xero can do, I'll investigate
* In terms of getting the data out of Xero exported into a spreadsheet, it's actually very easy:
  * Go to Reports > All Reports > Accounting > Account Transactions
  * (It's important to get all `transactions`, and not to only look at `invoices` because Casper's put a lot of the `transactions` down to "Spend money" rather than "Pay invoice" - pretty annoying, but not much we can do about it at this stage) 👻 
  * Now you'll be on the report settings page. Select `412 - contractors` from the `Accounts` dropdown, fill in the time period you need, and then click "Report Settings", bottom right to open the advanced settings
  * Leave all the settings as they are, but make sure that `Client` (and `sprint` if you like) is ticked under `Columns`
  * Run the report by pressing `update`, and then export the results to `google sheets`
  * Once in a spreadsheet, you can filter/order by date, client, sprint
  * In order to filter by Contractor, you need to do `text to columns` on the Reference column, with the separator being ` - ` 

Over to you @iteles 😸

**Comment by iteles** [comment]
This was emailed and we're awaiting our R&D consultants' response.
Bumped down the priority so it doesn't scare me every time I see it!

**Comment by nelsonic** [comment]
![nice](https://media.giphy.com/media/pCO5tKdP22RC8/giphy.gif)

**Comment by iteles** [comment]
Just received from consultants:
> Please could you provide the accounts, tax computations and CT600 tax returns both for the years ended 30 April 2016 and 30 April 2017.

@rub1e Could you grab our CT600 (corporation tax return) from the HMRC portal for 2015/16 and 2016/17 please?

I've got the rest on file - let me know where to drop it in the G-Drive!

**Comment by rub1e** [comment]
@iteles The CT600 returns aren't available online - you have to ask for them from HMRC and they'll post it to you which, according to the forums, takes around three weeks.

So I can do that or perhaps if we reply asking what exactly they need, we might be able to run a report in Xero that has all the relevant data.

If you want to just loop me into the emails, I can take it up with them

**Comment by iteles** [comment]
Email sent but got an out of office until 16th April. 

Let's ask for them anyway, worth having on file.

**Comment by iteles** [comment]
@nelsonic We've just been sent a spreadsheet to add the list of projects templates with a few examples of the different projects that fall within the outlined project categories (we can add any that fall outside those categories as well).

We've also been asked:

> Additionally, if you could provide more technical information on the case study project (HL) in relation to the technical challenges faced and the different alternative solutions you experimented with that would help for the technical report.

Weekend fun? 😬

**Comment by iteles** [comment]
@nelsonic I've filled in the project names, but could you please fill out columns J & K? (note the notes in column N)

I'll fill in the others tomorrow.

**Comment by nelsonic** [comment]
@iteles which _rows_ do I need to fill? (_**all** of the **blank** ones?_)

**Comment by nelsonic** [comment]
@iteles I've filled in the cells for the relevant columns/rows. please take a look and leave a comment where anything else is required. thanks. 👍

**Comment by iteles** [comment]
Got confirmation today that they finally have all the info they need (after a couple of phone calls of project-specific questions).

I have also emailed our accountants to confirm that they are happy to file this at the end of the week.

Almost there!

**Comment by iteles** [comment]
Finalising CT600 paperwork.

**Comment by iteles** [comment]
All done, R&D consultants and our accountants are in touch, everything is agreed and we're good to go.

**Comment by nelsonic** [comment]
https://getyarn.io/yarn-clip/dfa11304-87d0-45ec-8ec3-7d49bedfc76d

**Comment by iteles** [comment]
🙄

**Comment by iteles** [comment]
Done and filed!

Thanks to @nelsonic for filling in all the technical challenges and complexities for relevant projects and 
Thanks to @rub1e, thank you for doing _all_ of the pulling together of data from `all the places`, making my estimating job really easy. Gotta have data to make the decisions! Your initiative is MUCH appreciated.

**Comment by Mihailoff** [comment]
It is quite impressive to witness #HyperTransparency in action!

@iteles you can check out [Quantify](https://github.com/qntify) to see how they are solving this "reporting hell" problem.

**Comment by rub1e** [comment]
We've now got all the money back from HMRC; it matches roughly with what we're expecting (we actually got ~£150 more than expected, because HMRC paid us interest!!)

I'm just reopening this because I've added one more task - to check & reconcile these figures. 

And I just need one more letter to arrive from HMRC with some calculations on it before this can be closed off entirely (for some reason they made the payment in two batches, and I've only got the calculations for one batch)

**Comment by rub1e** [comment]
I still haven't had the second letter off HMRC but I'm inclined to close this anyway, as the figures from the R&D consultants plus the interest added on precisely matches what we were actually paid by HMRC

I'm speaking to them tomorrow so I'll ask if we're due a letter from them, but if not I'm happy to close this off.

**Comment by rub1e** [comment]
I'll pay the last R&D invoice and close this off when I do our next pay run

In the meantime, the consultants got in touch to ask about the 2018 claim. I've got a mate who said he was doing the claim for his business and that it's really not too much work - so I asked him to send over any info I might need. He sent me a bunch of stuff, before revealing that he didn't bother doing it himself and just paid a consultant to do it!

So I'll do a little spike to review what he's sent over and see how feasible it is for us to do the next one ourselves (for #481 )

**Comment by rub1e** [comment]
All payments have been reconciled and all invoices have been settled

Happy to close @iteles ?

**Comment by iteles** [comment]
@rub1e 👍 Thank you! Closing as the write-up is captured in #481
