### ISSUE TITLE
Potential new mini project | BEP website

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#439]
Having built the [BEP app](https://github.com/dwyl/bestevidence/), CU are looking to build a static website to promote it or have as a gateway into the application.

The budget for this is _tiny_ so we will be looking to reuse as much of the work we did for the Quodl website as possible.

## Tasks
+ [x] Initial call
+ [x] Follow up summary of potential agreement
+ [x] Agreement on scope 
+ [x] Estimate budget
+ [x] Send through budgets
+ [x] Discuss project with dwylers and determine interest/availability
+ [x] Agree timelines
+ [x] Send contracts to dwylers

**Comment by iteles** [comment]
Proposed starting point for scope sent, awaiting reply.

**Comment by iteles** [comment]
Current scope for estimating:
+ **Homepage**
  + Similar sections to Quodl but replace the section with the Quodl badges with a video demo of the product in action or some text with screenshots
  + Remove blog section at the bottom
  + Quotes from people who have said how good the app is - new functionality, ideally there would be a bank of these and they would randomly swap themselves out, but this should be estimated as an extra
  + Something on importance of evidence-based practice and how app fits, possibly in an existing section
+ **About** - keep this page and ensure content is updated
+ **New Page** - Something on how to appraise papers: validity, results, relevance
+ **New Page** - Page with embedded graphics from redash (can be just screenshots that PO updates through CMS at a push but ideally not)
+ **Pricing** - we maintain this layout as is and just update the content to reflect BE
+ Replace blog page with 'Latest Publications' (exact name of page TBC)
  + We either: 
    + Keep the blog 'format' where the 'Latest Publications' page has a little box for each of the publications/studies etc (like http://quodl-site.herokuapp.com/blog) and then the visitor clicks into the titles of the ones they want to know more about (I would recommend this)
    + Create something more akin to the 'About' page, but I think this could get a bit too long - other layouts can be explored
+ **How to use BE** - this is a new page, following the contents of the PDF guide Amanda sent through
  + Format would be similar to the Quodl About page
+ **New page** - Examples of questions and successful use of app with people able to submit own examples to us
  + Examples of successful use are longer stories with a clinical background, detailed search, explanation of why a a particular paper was selected, how it resolved an uncertainty and different to the testimonials on the homepage
+ **Contact** - Same as the current one: http://quodl-site.herokuapp.com/contact

**Comment by iteles** [comment]
Thanks @Cleop @RobStallion and @parkhabit for estimating!

Sent to CU 👍

**Comment by iteles** [comment]
Confirmed!
@parkhabit will be starting on this today, with @RobStallion joining her tomorrow 🎉
