### ISSUE TITLE
Potential new project | Good Thinking extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#440]
An interesting mental health project we worked on last year (Wagtail, python, HTML/tachyons) has come back to us for an extension of features, including search.

## Tasks
+ [x] Initial list of features
+ [x] Call with @Danwhy and @shouston3 to determine level of python skills required for the feature list
+ [x] Discuss project with dwylers and determine interest/availability [in progress]
+ [ ] Agreement on scope
+ [ ] Send through budgets
+ [ ] Agree timelines
+ [ ] Send contract to client
+ [ ] Send contracts to dwylers

**Comment by iteles** [comment]
Waiting for next steps from client on scope which they are currently refining.

**Comment by iteles** [comment]
The NHS decided to just carry out maintenance of the service rather than augment it for now. We can reopen this if they change their mind.
