### ISSUE TITLE
Sorting and filing mail from 2017

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#441]
We inherited a large stack of post (mostly still in envelopes) from Mark in Dec-2017 and still have a smaller stack of post (again, opened but still in envelopes) from the 3 months we were out of the country late last year.

These need to be taken out of envelopes, sorted and filed into the relevant dwyl folders.

## Tasks
+ [ ] Write VA brief
+ [ ] Book time with TaskRabbit
+ [ ] Filing of mail happens!

**Comment by iteles** [comment]
We had a lovely non-virtual assistant come in for half a day today to take care of our 2017 mail.

She managed to:
+ Get everything out of envelopes
+ Sort all of the mail into various related piles
+ Sort all the piles in chronological order
+ Hole punch 2/3 of the papers

![img_7927](https://user-images.githubusercontent.com/4185328/36742325-4af4499c-1bdf-11e8-9dc0-fd04fcf67071.jpg)

**Next steps:**
+ Hole punch the rest of them
+ Determine order in which to file
+ File papers


_This shouldn't even have had to be a job - mail should be sorted and filed whenever it comes in,_ therefore preventing a 2 minute task from turning into a multiple hour task and a year of never quite knowing whether we have the paperwork for particular things.
From now on, that's what we'll be doing of course.

**Comment by nelsonic** [comment]
@iteles did you manage to _find_ a Hole Punch? (_or do you want me to pick one up from Ryman's_) ?
