### ISSUE TITLE
Potential new functionality | QL site & app payments extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#444]
In order to transform QL into a paid application, changes will need to be made to both the website and the application.

## Tasks
+ [x] Initial team conversation on general flow of tasks that need to be completed
+ [x] Request clarity from client on tiers of pricing/functionality
+ [ ] Understand CU payments API **[in progress]**
+ [x] Initial estimates created
+ [x] Initial estimates & budget sent
+ [x] Agree timelines

**Comment by iteles** [comment]
@sohilpandya @jessicasalmon Assigned this one over to you as you're in the process of creating the estimate 👍 

I'l keep chasing the payments non-API to see how we would get info back from them on what has been paid.

**Comment by sohilpandya** [comment]
**Free Plan: T2d**
- Create a new url for lecturers to sign up, currently this is only accessible by Stian, we need to make this public T4h
- Add a new column in user database table for setting a trial version. T1.5d (not including d)
    - We can have a trial column (boolean), expiry time
    - Check these and if users out of trial time then log user out. 
    - When user tries to log in, check for the trial time, and display message to upgrade account with a link to upgrade. 
    - Once user pays (separate flow) we can then switch the toggle when the payment is made. This is a separate flow and will need to be dealt with when payment is made for individual users.  

**Paid Lecturer: T1.5d (not including 1)**
- Once the user pays, we need to provide them a code this happens outside of this flow
- In the newly created lecturer  sign up flow, we add a new optional field called code/secret/something…
- When the user tries to sign up, we check if the code exists and is valid, 
    - If it is valid. Need to create a new table which contains payment details including a code. (this will be dummy for testing purposes, but will need to be linked to payment flow)
    - a limit has not been reached (i.e. whatever limit we set, it will check if that many users have already signed up), then we take the user in
    - If it is not valid, then we show a message and ask them to enter a different code or sign up as a trial. 


**Group Admin: T1.5d**
- Create a new column in user database called group_admin(boolean).
- If a user has paid, we should have the email address under which they paid. When user pays we need to ask for the email address which they will use to sign up and put this in the payment table. 
- When a user signs up we also need to check if the email address exists in a different table payment table. (which will need to be created) If it does exist in this table then we can set the group_admin to true, as they have paid for a plan. T4h
- This user will have a new area called admin (different to super admin) 
    - Where they can see all the lecturers that are using the code related to them.
    - They will also be able to delete this user.  T1d

**Authentication:  T1d**
- Generally, we need to change the flow of authentication for lecturers, we need to check if they have valid access, if they do then continue, otherwise log user out. This will need to be done as well 
I guess this is where we also need to check if the user has paid the monthly fee, if the group admin has paid then give access, otherwise log user out and provide a message saying please pay.. 


**General Thoughts, Things we may have missed:** 

Something we haven’t thought of if an individual on a free trial gets signed up by an institution, where would they add the code? 
**QUESTION FOR STIAN:** What do we do to all the existing lecturers, what do we need to do to them? Do we set them as legacy users, so they all have the same access? We need to ask this. This will involve some time from us to setup.  

**Payment: (not scoped)**
Haven’t even thought about this, but it is vital, no matter what we decide to use, we need to have one thing in place. 
When a user pays, we need to create a column in a new table (payments) inside of the database, this will contain information related to the user who paid, the unique code, expiry date. All this information is vital and will be required in almost all of the points above. 

**Total Time: 6 days not including payments.**

**Comment by iteles** [comment]
Thanks @sohilpandya ! I'm following up with them as we speak on payments.

**Comment by sohilpandya** [comment]
**Additional Super Admin Functionality: T2d**
- All payments will be done manually, so we need to have an area where the super admin can add a client. 
- Super Admin will navigate to the super admin area
    - Add a new button called ‘add a client’ 
    - Provide a form with the following fields:
        - Name
        - Email
        - Account type: Group (in which case add group_admin to true) or Individual which will not do anything here.  
        - Paid: Yes/No 
        - Code: This will be generated when the user is created 
- When the user is saved, we will need to do two things:
    - Create a user with that name, it will automatically call the add new user flow, set group_admin as true, the given user will then receive the confirmation email and can follow that to log in etc. 
    - Create a new row in the payment table, with the user, paid and unique code, linking to the given user. 
    - We also need to run checks to see if this user already exists and if they do then prompt a warning and ask the user to edit the existing user. 


- We also need to allow the super admin to edit lecturers,
    - This will happen from super admin home screen where they can already see a list of lecturers
    - When they select edit, they will be taken to the details section
    -  so that they can switch the paid to No if the user stops making payments. And edit any other details if necessary. 
    - This will then affect the rest of the users who are attached to the given group. 


**Please let me know if we have missed any additional fields out.** 
Idea is to use the paid and code fields to check if a given user should have access if they do then we let them continue, otherwise we log them out. 

@jessicasalmon @iteles please have a look and let me know if the above estimates make sense and are ok 👍 or if I've missed something out. :)

**Comment by iteles** [comment]
@sohilpandya 

For **Individual plan** (rather than an individual signing up as part of a group), I don't think they need a code, we should just be able to see they've paid for the individual plan and set the permissions up accordingly. It only really makes sense to have a code if you're tying yourself to a group plan.

All looks good! Thanks so much for this.

Budget sent.

**Comment by iteles** [comment]
For now we will be implementing this with _manual_ payments, no changes to be made to the website itself.
