### ISSUE TITLE
VAT Return | Feb 2018 to end Apr 2018

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#446]
VAT return for the period of 01.02.2018 - 31.04.2018.

**Deadline:** 1st June 2018.

VAT return and payment deadline is 7th June but this task needs to be completed ahead of time so that we can ensure the correct funds are available in our outgoing account for this date.

Low priority whilst we are waiting for the period to finish, but will be revised in May.

## Tasks
+ [x] Make sure all expenses for the period are entered
+ [x] Document the steps for this tasks ([what we currently have](https://github.com/dwyl/process-handbook/blob/master/finances.md#vat-return) is looking a bit abandoned)
+ [x] Submit the VAT return

**Comment by iteles** [comment]
Completed with https://github.com/dwyl/process-handbook/pull/99 👍
