### ISSUE TITLE
End of tax year (5/4/18) tasks

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#447]
* ~[ ] Claim Small Employers' Relief?~
* ~[ ] Set up statutory pay?~
* [x] Claim employment allowance?
* ~[ ] Submit forms P11D and P11D(b) for expenses and benefits [guide](https://www.gov.uk/government/publications/paye-end-of-year-expenses-and-benefits-p11d-guide) & pay any Class 1A NICs~
* [x] Update all dwyler tax codes (#442 ) (check for forms P9T/P9X from HMRC)
* ~[ ] Update NI category?~
* [x] Generate P60 for all employees and send
* [x] Split PAYE, student loans, and NICs on Xero (#449)
* [x] Check that total paid to employees + total paid to HMRC matches the total going out of our bank account.
* [x] Check employees' addresses up to date
* [x] Check director status up to date
* [x] Check student loan info up to date
* [x] Run gross to net payroll report `(reports > all reports > payroll > gross to net)`.  Select all employees and use the custom date range and change for the tax year i.e. 01/04/17 to 31/03/18
* [x] Run account transaction accounting report `(reports > all reports > accounting > account transactions)`.  Select accts 814, 825, 826, 947, 477, 479
* [x] Download P32 report `(payroll, taxes & filings, download P32)`
* [x] Open issue for April 2019 - https://github.com/dwyl/hq/issues/515

(NB: do *last pay run of the old tax year* AND *first pay run of the new tax year* as early as possible as a *draft* just so we have a bit of time in case anything goes wrong with the new tax codes etc.)

**Comment by rub1e** [comment]
#### Small Employers' Relief
We don't qualify this year because we'll go above the threshold for NIC payments in month 12 (so we definitely won't qualify next year)

#### Statutory pay
Not relevant this year

#### Claim Employment Allowance
This is done in Xero by going to `Settings > Payroll Settings > HMRC` and ticking the box that says you'll claim Employment Allowance

 #### Submit forms P11D and P11D(b)
We have no relevant benefits or expenses 

#### Update all dwyler tax codes (#442 )
The basic formula is to add 35 to all tax codes ending in L, but we should be sent a P9T form from HMRC with all the details for employees needing new tax codes

#### Update NI category
No one needs this changing this year

#### Generate P60 for all employees and send
Xero does this for us. Go to payroll, select all employees, and hit `send P60`

**Comment by rub1e** [comment]
After an exciting call with our bookkeeper, I'm please to report that the above is correct!

The only thing I've added to the checklist is #449 and the associated checks

**Comment by rub1e** [comment]
UPDATE: I've added some bullets from our bookkeeper with detail on the reports we need to run in Xero to check everything adds up correctly.

This video was also recommended: https://player.vimeo.com/video/207666197

**Comment by rub1e** [comment]
UPDATE: all *pre* end of year tasks are complete, and the final payroll of the year will be posted tomorrow.

Just to capture one thing here (this will be written up into a process), there's a very good reason to do all this reconciliation and checking well in advance of the end of the tax year:

If there are any discrepancies - e.g. @iteles embezzled **£3** in her December pay packet (claims it was a typo 😑) - they can be accounted for in the final pay run of the year

(Rather than creating *ad hoc* transactions to account for them *after* we've made a submission to HMRC)

**Comment by rub1e** [comment]
> The tax year is over! Long live the tax year!

HMRC documents have been filed, staff have their P60s, basically we're all squared away for 2017/18 🔲 

All that's left now is to document this mammoth 🐘 

😑

**Comment by iteles** [comment]
@rub1e Loving the use of emojis, very dwyl 😉 
And hooray! 🎉 Thanks for all the hard work on getting all the admin and legalities set up and squared away here, working only 2 days a week no less! You've done a fantastic job 👍
