### ISSUE TITLE
BE project extension 

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#454]
BE is applying for funding to make their evidence-based medical care application commercially viable. This involves a small number of somewhat complex features which require a lot of review with the PO to properly estimate.

## Tasks
+ [x] Review initial proposed set of tasks 
+ [x] Document extensive questions for clarification
+ [x] Call with PO for clarifications
+ [x] Call with PO to plot and clarify user journey for CATs
+ [x] Estimations of work with dwylers
+ [x] Send estimates to BE
+ [x] Receive response on whether funding was successful

This amounts to almost 3 sprints.

**Comment by iteles** [comment]
Funding for this has been approved _in principle_ but keeping this issue open until we have a definite answer and a date.

**Comment by iteles** [comment]
🎉 Work begun on this May 10th with @RobStallion and @sophielevens, @Danwhy as QA 😊
