### ISSUE TITLE
Ox project extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#455]
Ox have come back to us to ask for an extension of the mental health application for children we built for them last year.

## Tasks
+ [x] Agreement on scope
+ [x] Discuss project with dwylers and determine interest/availability
+ [x] Estimations for features
+ [x] Send through budgets
+ [ ] Receive response on budget and timelines
+ [ ] Agree timelines
+ [ ] Send contract to client
+ [ ] Send contracts to dwylers

**Comment by iteles** [comment]
Budgets sent through on 29-Mar-2018 (a little late creating this issue 😬), estimates carried out by @RobStallion and @parkhabit 👏

**Comment by iteles** [comment]
Chased again but they're in no hurry! Still waiting for a response.

**Comment by iteles** [comment]
Unlikely this will go happen at least for now given some big changes at the NHS.
