### ISSUE TITLE
EMF CE100 project extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#456]
Following on from user testing of #343 and with GDPR on the horizon, EMF are keen to further develop the application we have been building with them over the last 1.5 years.

## Tasks
+ [ ] Review request & return questions on scope
+ [ ] Estimations for features
+ [ ] Send through budgets
+ [ ] Receive response on budget and timelines
+ [ ] Agree timelines [current request is mid May to early June start]
+ [ ] Send contract to client
+ [ ] Send contracts to dwylers

**Comment by iteles** [comment]
Finalising timelines: 21st May or 28th May.
