### ISSUE TITLE
FY17/18 Year End Accounts

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#461]
These are due at the end of December 2018 at both Companies House and HMRC.

The first task here is to review what we have and make a list of tasks required!

@rub1e Let's both add to the checklist below please 😊 

## Tasks
+ [x] Make sure all of our invoicing to clients is up to date as of 30th April 2018
+ [x] Ensure all our outstanding expenses are paid by 30th April
  + [x] Get F&C invoice sorted #460
  + [x] Help Focus Hub pay the rent if needed
  + [x] Reconcile all VAT-relevant transactions, complete VAT return and pay out #446 
  + [x] @iteles to make sure all of her expenses for the quarter are in by the end of the financial year - and paid for 
  + [x] All dwylsummer expenses to be in by the end of the financial year - and paid for
  + [x] Confirm all dwyler invoices have been paid
  + [x] Run and pay payroll
+ [x] ** All *non-VAT* reconciliations completed in Xero **[In progress]**
+ [x] @iteles to confirm all FY17/18 expenses are in the system **[In progress]**
+ [x] Issue dividend share voucher for Mark (not required for Ines & Nelson as we didn't take any dividends) - this should be quick once we're nearing the end of the accounts as exactly the same thing happened the previous financial year 
* [ ] Document process

**Comment by rub1e** [comment]
We have a potentially sticky wicket to handle with the VAT for this period:

It seems that we've either been over-paying or under-paying for VAT for over a year - basically the last time our VAT account was balanced was May 2017!!

HMRC are sending me a VAT ledger (whatever that is) and I'll go through it and try to find the source of the error

@iteles I might ask for your help, because the account became unbalanced pretty much as soon as you handed over responsibility for it last year

**Comment by rub1e** [comment]
The VAT ledger has arrived - mercifully our entire VAT history fits onto a single page of A4... but the explanatory notes to the ledger cover 4.5 sides of A4 😆 😟

**Comment by rub1e** [comment]
I'll have to check this again and confirm it with HMRC directly, but the ledger was actually really helpful and this took no time at all

Basically our account was perfectly balanced until 18th May 2017, and then it *somehow* becomes unbalanced.

The culprit seems to be the practice of transferring HMRC our VAT payments but rounded to the nearest £5k - so we're always in credit. 

Spookily, this practice seems to have ceased in December 2017 - presumably something to do with a change in personnel? 

Anyway, hopefully it's just a matter of asking HMRC to apply our credit to the next return we complete (#483) 🤞

**Comment by iteles** [comment]
@rub1e Fantastic, thank you for getting to the bottom of this.

We have a month after the end of each VAT period to put together the returns and we always open the issue for the next VAT period as we close the current one so I expect it won't be too hard to continue to stay ontop of this for FY18/19 👍

**Comment by iteles** [comment]
@rub1e Had a call from our accountants saying they can now go ahead and issue the dividends voucher (as I mentioned, this is only needed for Mark and Nelson and I didn't draw any dividends from the company in FY17/18) so we can soon cross this off the list 👍 

Thanks for getting us into a position where we're far enough along with the final bits and pieces to do this! 🙌

**Comment by rub1e** [comment]
Update ref https://github.com/dwyl/hq/issues/483#issuecomment-413217686

I'm also taking advantage of Xero's free trial of their new expenses system to input relevant receipts, which will hopefully streamline the process a bit and allow me to enter expenses on behalf of others

**Comment by rub1e** [comment]
I've now sorted through a load of 17/18 receipts (and put aside a load of 18/19 ones)

I'm just waiting to hear back from Xero about using the expenses app to enter expenses on behalf of others - turns out that processing it through the app submits them with the `spent by` field locked to the submitter. Which is pretty dumb, but hopefully there's a way around this (the expenses app automatically processes receipts, so is a massive time-saver, especially for int'l receipts)

**Comment by rub1e** [comment]
Update:

* All bank transactions have been reconciled, except for a shortlist which I've shared with @iteles and @nelsonic 
* All paper receipts out of the main account have been captured

Remaining:
* @rub1e - capture remaining expenses receipts in London and reimburse @iteles 
* @iteles - capture remaining expenses receipts in Portugal

**Comment by rub1e** [comment]
Just finished adding details and approving all of the expenses using the much-vaunted expenses app. It took ALL MORNING, even though the app had already analysed the receipts.

Having now had more of a chance to play with it, I'm not convinced that it's the silver bullet I thought it was - it's patchy on everything from VAT to GBP/EUR to dates to amounts. That said, it's still (much, much) better than nothing!

(One thing I've noticed though is that VAT registered companies don't always give you a VAT receipt as standard - so there are things we can't reclaim VAT for because we don't have a receipt that has VAT clearly marked on it. So we should be getting into the habit of always asking for a VAT receipt, and I'll add a note about this to https://github.com/dwyl/process-handbook/issues/106)

Finally, @iteles because the app won't let me assign the expenses to you, they're all under my name - but all we need to do is pay the money to you and reconcile the transaction that way.

**Comment by rub1e** [comment]
Situation so far:

* Every bank transaction up to mid-november 2017 has been reconciled (yay!)
* There's only about 20 transactions left to reconcile, and the majority are ones we already know about (heroku, 3 Mobile), or ones I'm keeping open just on the off-chance that we find a VAT receipt for them so  we can reclaim VAT
  * Heroku - I've recently discovered that these invoices are subject to the `reverse charge` process which means we don't technically need VAT invoices. (But we've never figured out which account this charge is attached to, which might be nice.)
  * 3 Mobile - given that this is a business phone contract and definitely has VAT added, I'd be comfortable reconciling these and reclaiming VAT if we're not able to locate the VAT invoices at this stage, **as long as we know we can find them if we need to in case of an audit**
  * And the remainder are ones with uncertain VAT status, so if the worst comes to the worst these can be closed off without reclaiming VAT

So as far as Xero we're in a _really_ good place; the main thing is now to get the **expenses** settled

I shall also check that I've not cheekily put anything into the `suspense` account that now needs to be updated and categorised correctly

**Comment by rub1e** [comment]
OK I've been through all the receipts now and made sure they're correct. I've also added an `IVA` label to the Portuguese receipts so I can go through them and add up the tax paid in case it turns out we're able to reclaim IVA (#484)

So now they can be settled whenever we like!

**Comment by rub1e** [comment]
### Payroll reconciliation

Because of dwyl's `accounting period` (year to 30th April) overlapping with the tax year (year to 5th April), an extra month of payroll needs to be reconciled

Annoyingly, this is the exact time our pension scheme started, so refunds/opt-outs have to be processed first, and the first pensions payment categorised correctly

**Comment by rub1e** [comment]
Payroll was mercifully easy as we didn't actually _pay_ the pension provider until much later - so this was just a matter of reconciling the wages and tax as usual

(That said, I'll still have to deal with pensions/refunds and write up the process, just not for FY17/18)

General update: it's just filling gaps now - there's... less than one page's worth of reconciliations; a couple of boxes of receipts; general checks. I reckon we'll be able to send this to the accountants the week before Xmas 🤞

**Comment by rub1e** [comment]
Weekly update - not to brag, but I smashed through my box of receipts today. Once the rest are done, I'll go through adding correct references / accounts / labels etc. and then we can pay all of the FY17/18 expenses in one go.

There are a handful of items in the `suspense` account which I need to investigate, but otherwise this is straightforward.

**Comment by rub1e** [comment]
State of play:

* I've edited and approved all of my receipts
  * My love affair with the Xero Expenses app has well and truly ended. It can get the name of a shop in Greek right, but not a date in `yyyy-mm-dd` format. All receipts must be checked manually.
  * Amazon's `Business Analytics` system was sent by the Devil to test me
* Ines will submit all of hers for approval (they're already uploaded in `drafts` and then I can edit and approve them (or send back if anything is unclear) 
* I've sent a couple of queries to Ines, but there are only two unreconciled transactions left in the whole financial year 😊 
* Everything in the `suspense` holding account has been assigned to an account and dealt with, except for:
  * £50 to HMRC which I just CANNOT figure out and I'm getting quite MIFFED about it
  * Dividend payments to former directors, which we'll leave to our accountants to deal with

**Comment by rub1e** [comment]
The only thing to add to the above right now is the Expenses process I've been following:

* For UK expenses, put `No VAT` if VAT isn't clearly marked on the receipt
* For EU expenses...
  * Always mark as `No VAT` (or Xero will try to reclaim it from HMRC)
  * If IVA (Portuguese VAT) is clearly marked, then add the label IVA
  * Also if you feel so moved, I've been adding up the IVA for each receipt and writing it in the description, so that we can easily add up IVA if/when we come to reclaim it
  * Double check the date - Xero isn't picking up the difference between 2017 and 2018
  * Double check the currency - sometimes it gets it wrong

**Comment by rub1e** [comment]
As discussed @iteles it looks like there's a permissions issue with me approving your expenses. Issue has been raised with Xero, but in the meantime...

* I've been through every one of your receipts and corrected dates / VAT rates
* They should all appear with `approval timed out` on your expenses page
![screenshot 2018-12-19 at 15 26 23](https://user-images.githubusercontent.com/11595920/50236305-f2da5380-03b1-11e9-875f-fb598791e3e7.png)
* If you want to approve them, you can do so in batches - `approve the next 50` link at top right
![screenshot 2018-12-19 at 17 18 56](https://user-images.githubusercontent.com/11595920/50236413-3e8cfd00-03b2-11e9-9816-eeee6d89607b.png)
* But if you want to wait until you've searched through your emails for any stragglers, hopefully Xero will solve the issue by then

**Comment by rub1e** [comment]
After Xero straight up lied to me and said they'd checked and I didn't have permission for expenses, they "checked" again and the approval issue is because @iteles is so pretentious she insists on spelling her name correctly.

The solution is for you to log in and change your name to remove the circumflex accent*, and then I'll be able to approve the expenses.

Once again, they are asking the user to do a workaround rather than fixing the bugs in their product themselves 🙄 

*Top right hand corner, there will be a roundel with `IT` - click this then "edit profile"

**Comment by iteles** [comment]
This will certainly be faster than them fixing it on their side though.

Done. Now pretentiousness-free 💁

**Comment by rub1e** [comment]
Thanks for this - all expenses now approved.

Thanks also for telling me you found another box of receipts and I'll be back at it tomorrow 😭  (I can't do receipts right now because of the below)

![screenshot 2019-01-08 at 17 15 54](https://user-images.githubusercontent.com/11595920/50847409-6a742080-1369-11e9-84ee-d7e96f611b08.png)

Xero's advice if you can't use Euro is to just use Sterling. I mean, Brexit's taking it's toll but it's not _that_ bad. Yet

**Comment by rub1e** [comment]
Accounts were submitted last week and our accountants are going through them this week

Added task to document process for next year

**Comment by iteles** [comment]
We received draft accounts from our accountants on Saturday and are reviewing them with them again today.

**Comment by iteles** [comment]
Accounts submitted by accountants today and any corporation tax due has been paid.

@rub1e What do you need from  me in terms of documentation so that we can close this off?

**Comment by rub1e** [comment]
https://github.com/dwyl/process-handbook/blob/master/Finances/preparing-accounts-for-your-accountant.md

I'll add in the R&D section now, and then go over to see if we've missed anything relevant

The only thing I need from you is if there were any issues you went through with the accountants directly?

If you've anything to add, just let me know 👍

**Comment by iteles** [comment]
Nothing specific, it changes every year based on what they send back and  needs reviewing. More of a question of understanding where the figures come from. I'm taking up the question of getting Xero sorted with them too so I'll open  a separate issue for anything that comes of that.

**Comment by rub1e** [comment]
PR https://github.com/dwyl/process-handbook/pull/143 ready and awaiting review (no rush!) and all tasks have been transferred to #525 for FY18/19 so this issue can be closed.
