### ISSUE TITLE
EPIC: Moving into Space4

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#469]
What sort of things do we need to think about before moving into Space4? Please add to this list, even if it's just questions

* [x] Do we need a lockbox for private documents etc.?
* ~[ ] Do we want to have a dedicated phone number?~
* [x] Contents insurance - #256 
* ~[ ] Mail forwarding~ 
+ [x] Update the address on Google My Business
* [x] Change address on Santander bank account (need to wait until confirmation of change of signatories)
* [x] Change address on Coop bank account
* [x] Change address on Pension provider (requested 26/6)
* [x] Change address on all HMRC / CH services

* [ ] Turn this into a general checklist for when we move premises

**Comment by rub1e** [comment]
29/5 

Contents insurance requested from our existing provider Digital Risks. Fairly limited in terms of what we need cover for, and DR will try to do it for free as a gesture of goodwill after failing to respond to several of my emails.

Mail forwarding decided against because it's very expensive and we still have access to no 16 to pick up our post ourselves

**Comment by rub1e** [comment]
We're here, we're insured (#256), Google is processing the address change... any reason to keep this open @iteles ?

**Comment by iteles** [comment]
Nope!

**Comment by rub1e** [comment]
Reopening because we need to change the addresses on our bank accounts

**Comment by rub1e** [comment]
Added changing address on government websites (again) because it seems they treat various services (VAT, PAYE etc.) differently and you need to manually change both office address and postal correspondence address separately

So even though we've changed our address on some systems, it hasn't `propagated` through to others

Will tick after 48 hrs when have confirmation

**Comment by rub1e** [comment]
Santander [form](https://www.santander.co.uk/csgs/StaticBS?blobcol=urldata&blobheadername1=content-type&blobheadername2=Content-Disposition&blobheadervalue1=application%2Fpdf&blobheadervalue2=inline%3Bfilename%3D166%5C771%5CANB90042.pdf&blobkey=id&blobtable=MungoBlobs&blobwhere=1314016431462&maxage=3600)

**Comment by rub1e** [comment]
Santander form printed along with documentation, so a handsome and witty courier has been commissioned to bring the document to Europe for signature and return it to Blighty for posting

**Comment by iteles** [comment]
@rub1e Address change request made for Coop as agreed.

I thought the Santander courier was so charming!

**Comment by iteles** [comment]
@rub1e I have also checked the top box for 'Change the address for Santander bank account' because when I called about #483, they confirmed the address change had gone through last week (30th August) 🎉

**Comment by rub1e** [comment]
PR for checklist: https://github.com/dwyl/process-handbook/pull/131

**Comment by iteles** [comment]
Reviewed and merged, thanks @rub1e !
