### ISSUE TITLE
PoC | QL in virtual learning environment

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#473]
We've been asked to come in to discuss a mini proof of concept piece around having QL work within City's virtual learning environment.

## Tasks
+ [x] Meet to discuss scope
+ [x] Initial meeting with LTI to discuss feasibility
+ [x] Agreement on scope
+ [x] Discuss project with dwylers and determine interest/availability
+ [x] Estimations for features
+ [x] Send through budgets
+ [x] Receive response on budget and timelines
+ [x] Agree timelines
+ [x] Send contracts to dwylers

**Comment by iteles** [comment]
First meeting booked: Tuesday 5th June.

**Comment by iteles** [comment]
General scope:
1. LTI Integration
2. Non-synchronous functionality
3. Performance and session management
4. Styling enhancements

**Comment by iteles** [comment]
We had a call with an LTI specialist and uncovered the many limitations of moodle when it comes to integrating with third party systems.

Further conversations are to be had on scope.

**Comment by nelsonic** [comment]
Also: https://blog.ripstech.com/2018/moodle-remote-code-execution 🙄

**Comment by iteles** [comment]
Scope for estimating:
1. Auth
2. Single item in gradebook
3. iFrame with public leaderboard for a module

**Comment by iteles** [comment]
Estimates discussed with @Danwhy, budgets sent through.

**Comment by iteles** [comment]
Moving forward with @Danwhy and @sophielevens 🎉
