### ISSUE TITLE
Research and Development tax relief for FY17/18

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#481]
We should review our FY17/18 projects whilst they are still fresh in our minds and determine which might be eligible for R&D tax relief, following on from #438.

## Tasks
* [x] Identify qualifying projects and populate `Project list` with basic info @iteles
* [x] Populate `Cost Collection` sheet with as much info as possible @rub1e 
* [x] Discuss %age of time spent by each dwlyer on R&D-qualifying activities and populate `Cost collection` sheet @rub1e & @iteles 
* [x] @iteles Review data:
  + [x] Initial review together - @rub1e and @iteles 
  + [x] Review time across projects for @iteles 
  + [x] Confirm which months are over or severely under the total working days for that month and double-check 
  + [x] Confirm which months are over the total working days for Nelson and double-check (if a person - Nelson - was working weekends, then we can ask the consultants)
  + [x] Fill in Mark's time for any support lent to projects administration
  + [x] @iteles to check Mark's support time on any eligible projects with @nelsonic as they worked together on a few things too which I don't have recorded
  + [x] Check all of May 2017 for all PAYE dwylers (time not being tracked anywhere leading to a makeshift excel sheet in a desperate attempt to capture _something_ when #363  went nowhere)
  + [x] Check totals across the board to make sure all time is accounted for (i.e. days in the month that were not on eligible projects are accounted for on holidays or non-eligible projects)
  + [x] @rub1e to fill in his time on administrative support for projects (including MW chasing)
+ [x] Get end of year tax computations from accountants
+ [x] Fill in descriptions for each project
+ [x] Decide which project will be the lead
+ [x] Email data to consultants
* [x] Email accounts, tax computations and CT600 tax returns
* [x] Consultants to send draft of tax relief paperwork
* [x] Review final draft
* [x] Email accountants the information
* [x] Approve filing
* [x] File for tax relief
* [x] Receive decision on R&D tax relief
* [x] Check & reconcile money received from HMRC against invoices from consultants

**Comment by rub1e** [comment]
Bumping up to `P2` as the consultants are nagging me to do a call about getting the ball rolling on this one

**Comment by iteles** [comment]
Don’t let them dictate the priority on this @rub1e, I’m keen for us to square away the accounts before we look at this.

**Comment by rub1e** [comment]
@iteles Totally - actually the main thing was for me to check the contracts and review my mate's reading list before speaking to them!

**Comment by rub1e** [comment]
Reading for R&D DIY

https://granttree.co.uk/how-to-file-rd-tax-credits-yourself/
https://granttree.co.uk/r-d-tax-credits-guide/
http://www.thisismoney.co.uk/money/smallbusiness/article-4402416/Could-claim-tax-research-development.html
http://www.g2innovation.co.uk/news/2015/7/29/how-long-will-rd-claim-take
https://businessn2k.com/rd-tax-credits-how-make-claim-hmrc/
https://simpleweb.co.uk/an-introduction-to-rd-tax-relief-for-startups/

**Comment by iteles** [comment]
@rub1e As we discussed today, it would be good to just find out from them if the information we need to provide is based on the same templates this year. If so, this is something I can start filling in whilst you're dealing with the fun of the accounts https://github.com/dwyl/hq/issues/481#issuecomment-416848749 and we can tag-team this 😉

**Comment by rub1e** [comment]
OK, I've reviewed the project list and the cost collection spreadsheet and it looks the same as last year (they've even pre-filled a couple of old project from last year)

@iteles the best thing is probably for us to have a quick chat over the phone how to divvy up the sections.

In the meantime, here is a rough task list:

* [ ] Decide which projects are suitable
* [ ] Populate spreadsheets with data for each project (ops and dev costs, proportion of time spent on R&D)
* [ ] Review data then send to consultants
* [ ] Email accounts, tax computations and CT600 tax returns
+ [ ] Consultants to send draft of tax relief paperwork
+ [ ] File for tax relief
+ [ ] Receive decision on R&D tax relief
+ [ ] Check & reconcile money received from HMRC against invoices from consultants

Documents are saved in finance > Corporation tax > R&D

**Comment by rub1e** [comment]
I've assigned this to you @iteles for the first task, please assign back to me when you're done and I'll pick up the `cost collection` side of things

**Comment by iteles** [comment]
@rub1e First pass done! 👍 

I've noted down as much as I can in terms of qualifying projects so passing back to you for dates. The company calendar will be your friend but you'll need to check invoices for Healthlocker, SMG, EMF and Quodl for the period between 2017/18 year beginning and the June start of the calendar please!

For the internal projects, I also noted down who worked on them in the column to the far right.

Note: Some of these will be continuations from last year, so you can also copy across the relevant project descriptions etc from the previous year!

**Comment by rub1e** [comment]
I've done as much of the project list spreadsheet as I can, adding dates, descriptions, and personnel where possible (I actually used github more than the company calendar - tells you exactly who worked on it and when! - just FYI)

I'll give it another once-over before asking @iteles about gaps

Now, regarding the `cost collection` sheet, I'm confused: since we're entering `X staff at Y%` figures into the `project list` sheet, are we then just re-entering that information in granular detail on the `cost-collection` sheet??

In which case, do we need to make sure they match up?

**Comment by rub1e** [comment]
Just a little progress update - almost ready to finish with inputting into the cost collection sheet, just waiting to hear back on a couple of queries from the Leyton team and then we'll be ready to populate the %age of people's time spent on each project

**Comment by rub1e** [comment]
Progress

* All staff details inputted
* All projects inputted into freelancer section
* All freelancers inputted into freelancer section with their project dates (stupidly, I should have done the gross amounts paid out at the same time as the dates)

Questions @iteles :

*  Looks like the `legacy` tab on the company calendar goes back as far as 19th June 2017 - which means I'm missing info for May 2017 and half of June. What did you do before the legacy calendar?
* I couldn't find anything for...
  * `TC Roam insurance` so I just took all TC invoices in the relevant period - is that correct?
  * `dwyl open source Swift app` - no external invoices, does that sound right?
  * `IOT-decibel` - could that be called something else?
  * `Datepicker` - no external invoices, does that sound right? (It's entirely possible people have just put down "dwyl" as the project)
* I'm waiting for responses from Leyton about the perm staff section - because if we have to break out every single project with days for each staff member, that will be very annoying... (Jenson is on holiday)

**Comment by iteles** [comment]
In answer to your questions:
+ Before the legacy calendar we had a different way of doing it that was not updated from February 2017 onwards when I handed it onwards; this is why I put together the calendar, just so we had _something_ to track it
  + The February to June 2017 void needs to be filled with invoices and my memory 😬 
+ Projects questions:
  * `TC Roam` - everything from October 2017 onwards for TC was this project
* `dwyl open source Swift app` - All Sohil invoices that should detail this in the invoices, these are the repos:
  + https://github.com/dwyl/learn-apple-watch-development
  + https://github.com/dwyl/time-apple-watch-app
* `IOT-decibel` - that is all Naaz, one day a week (PAYE)
* `Datepicker` - this was all Daniel, PAYE

**Comment by rub1e** [comment]
Note to @rub1e - for documentation of process - you can fix the dates of the invoicing sheet and manually add up amounts in the total column

**Comment by rub1e** [comment]
As discussed with @iteles just now, because the personnel on a project will all be spending the same proportion of their time on R&D-relevant activity, the simplest way of going about this is for @iteles to fill in the `Project List` sheet with topline information (e.g. "5 staff at 80% R&D") and then I can fill in the granular breakdown in the `Cost Collection` sheet.

* [ ] Fill in `project list` column L @iteles 
* [ ] Update @rub1e with details of which projects directors have worked on where it's not obvious from role tracking categories @iteles

**Comment by iteles** [comment]
@rub1e Preeeeeetty sure this is now done (I hope!). Left lots of comments, let me know where I can help.

**Comment by rub1e** [comment]
Yes, thanks for this! I'm prioritising getting the regular accounts done and then I'll hit this hard

**Comment by rub1e** [comment]
* Filling in gaps from the distant past - just use github! `https://github.com/[INSERT NAME}?tab=overview&from=2017-06-01&to=2017-06-30`
* Sense-checking
  * There are roughly 250 working days in a year, minus 25 days' holiday & sick leave, minus non-productive time - so each full-time staff would shake out at roughly 210-220 days of work per year, or 18 days a month
  * I've added a sum at the end so we can see monthly totals, and identify where the gaps are

**Comment by iteles** [comment]
Added checklist to 'Review data' point in top comment.

**Comment by rub1e** [comment]
Good news! 

### Level of depth needed in project descriptions
> you can get away doing detailed descriptions for the main ones with just a few bulleted advancements and uncertainties for the rest  

:raised_hands: :tada: 

### Weekends
We're doing the right thing in capturing the _actual_ days worked, but we don't pay overtime so it won't make a difference to how much we can reclaim. 

(My understanding is that capturing weekends will affect the _ratio_ of how much time is put to each project; ultimately we're talking about _employees_ with a _salary_, rather than freelancers whose cost changes with how much they work.)

**Comment by iteles** [comment]
For the documentation: We need  to get our accounts done and ready as early as possible after financial year end so that computations from these can be sent to the R&D consultants and then we won't need to amend our accounts post facto.

Computations received @rub1e, have added them to the  drive.

**Comment by rub1e** [comment]
@iteles I've filled in the gaps in both the `project list` and `cost collection` sheets. 

(Only `datepicker` was missing, as it only had two days of work on it in FY17/18 - the rest of was this FY)

So all that remains is for you/Nelson to go through the project list and add bullet points about uncertainties & challenges - I've highlighted in 🔶 ( 🍊 ) the bits where I think you should put fuller descriptions - the rest you can just do basic bullets as per [this comment](https://github.com/dwyl/hq/issues/481#issuecomment-459254639#)

**Comment by rub1e** [comment]
Having spent so long staring at this spreadsheet, I only just noticed that there's a section for spending on `Software Licenses`!

So just mentioning that in case we had any relevant costs that could go down there? (But given the open-source nature of our work, it's not likely to be a great deal)

**Comment by iteles** [comment]
@rub1e None that I can think of. @nelsonic Any on your list?

**Comment by rub1e** [comment]
@iteles I've added our Sketch subscription to the list.

Just thinking - if ops time counts towards the R&D claim, what about Xero and G-Suite?

I'll sent the consultants an email about this now

**Comment by iteles** [comment]
@rub1e Xero would make sense because it is how the financials and managed for every project (even internal ones). Let's see what they say 👍

**Comment by rub1e** [comment]
Unfortunately they say it's too generic an expense for R&D relief (which is kinda fair enough I reckon)

**Comment by iteles** [comment]
https://granttree.co.uk/how-to-write-a-kick-ass-technical-narrative/

**Comment by iteles** [comment]
Final doc for review arrived yesterday. Currently being reviewed.

Had a call this morning on various questions around resource allocation and figures (for example, understanding which freelancers were invoicing as themselves rather than through a company of their own).

Requested the more detailed P&L accounts, which I'm sending now.

**Comment by iteles** [comment]
Filed by the deadline last week.

Need to review when the work was handed to us and check dates against the invoice.

**Comment by iteles** [comment]
Invoice issued 28-Feb-2020 although work was only completed 4-Mar-2020. 

This will ultimately not make a big difference because we won't be paying the invoice until we've received the money from HMRC.

**Comment by iteles** [comment]
This was completed, accepted by HMRC and received. 

The consultants originally sent us the wrong numbers to file - a higher figure - which I caught and questioned on my review (and long before our filing). They had based their original invoice on this higher figure 🙄  so we're now still awaiting a credit note before the invoice is paid. The ball is in their court and the invoice will be paid when that comes in so closing this issue 👍
