### ISSUE TITLE
Reducing alcohol consumption website

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#485]
The folks running a movement to reduce alcohol consumption have been in touch to ask us to work with them on the next iteration of their MVP.

They have an interesting model where brands and venues offering alcohol-free or low-alcohol 'transition' drinks are featured and they are also sponsored by a few interested institutions like city councils and brands.

The budget here is small so my guess is that they may work with freelancers rather than an agency (particularly as it is CMS heavy), but as it's a particular area of interest, I was keen for find out more.

## Tasks
+ [x] Initial call
+ [x] Review of high level requirements
+ [x] Send a high level idea of potential scope to see if we might even be in the ballpark of what they need or if different partners might be best for them
+ [x] Receive response
+ [x] Follow up call with @iteles and @nelsonic 
+ [x] Final response
+ [x] Write contract (thanks @rub1e)
+ [x] Review contract
+ [x] Propose workshop days
+ [x] Agree workshop days
+ [x] Discuss and sign agreements with dwylers
+ [x] Book in workshop
+ [x] Internal kick off call

**Comment by iteles** [comment]
We're officially working with CS on this 🎉 
I have added some more tasks to the top issue so we can kick this off and close the issue.

**Comment by iteles** [comment]
Contract sent, currently confirming workshop days.

**Comment by nelsonic** [comment]
The reason I participated in the "pitch" for this project is: https://github.com/dwyl/health/issues/48
My _belief_ is that this Client/Partner is doing "_Good Work_" 
promoting a healthy alternative to Alcohol consumption.

**`if`** I write _code_ for this project it will be: [https://github.com/dwyl/**adoro**](https://github.com/dwyl/atm) & [https://github.com/dwyl/**atm**](https://github.com/dwyl/atm)

**Comment by iteles** [comment]
Workshop booked! Kick off this Wednesday with @harrygfox 🎉

**Comment by nelsonic** [comment]
@iteles could you please share some detail on:
a) What is the "budget" in days/weeks and how are we allocating it?
b) What is the delivery _deadline_ for the project (_exact date_)
c) Have we got a list of the _metrics_ the client wants to track (_what drives their "bottom line"_?)

**Comment by iteles** [comment]
@nelsonic Of course!
a) Exactly 3 sprints for a 2 person team (with QA & scrum master) = 30 working days
b) Mid October was the date they had requested, we should double check this
c) We don't as we haven't been able to get this yet. To date we have been told that they care more about having customers see and use the product and venue search than they do about their bottom line.

**Comment by nelsonic** [comment]
@iteles thank you for clarifying the “budget”.
Do we have a way of _visualising_ the “_burn down_”?

**Comment by iteles** [comment]
@nelsonic Sadly no _good_ way at the moment.
I personally need to keep track of this _somehow_ so I have a makeshift tracker [here](https://docs.google.com/spreadsheets/d/1HejQid3ZqaIK2iYzsv4SrD40UGWYa7qm1YSvMdcWfME/edit?pli=1#gid=1068312920) which I put together last summer in a desperate attempt to plug the hole whilst waiting for https://github.com/dwyl/hq/issues/363 and others to be finalised.

`CS` (dark green) squares denote this particular project.
