### ISSUE TITLE
QL Study plan & forum PoC

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#490]
In our final update to QL, we will be building in a study plan and a forum proof of concept.

## Tasks
+ [x] @iteles to review scope with PO
+ [x] More detailed scope received
+ [x] Further review of scope (@danwhy & @sophielevens 💯 )
+ [x] Agree time for spikes
+ [x] Carry out spikes (thanks @danwhy)
+ [x] @iteles to send over budget
+ [x] Agree budget
+ [x] Await PO
+ [x] Send out invoice

**Comment by iteles** [comment]
Confirmation received, will begin Monday 6th August @Danwhy
