### ISSUE TITLE
End of tax year 5th April 2019

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#515]
* [x] Claim employment allowance
* [x] Update all dwyler tax codes (#442 ) (check for forms P9T/P9X from HMRC)
* [x] Generate P60 for all employees and send
* [x] Split PAYE, student loans, and NICs on Xero (#449)
* [x] Check that total paid to employees + total paid to HMRC matches the total going out of our bank account.
* [x] Check employees' addresses up to date
* [x] Check director status up to date
* [x] Check student loan info up to date
* [x] Run gross to net payroll report `(reports > all reports > payroll > gross to net)`.  Select all employees and use the custom date range and change for the tax year i.e. 06/04/18 to 05/04/19
* [x] Run account transaction accounting report `(reports > all reports > accounting > account transactions)`.  Select accts 814, 825, 826, 947, 477, 479
* [x] Download P32 report `(payroll, taxes & filings, download P32)`
* [x] Document process & add checklist to `process handbook` (based on https://github.com/dwyl/hq/issues/447#issuecomment-372976440)

**Comment by rub1e** [comment]
Bumped priority as this is now two weeks away (that said, most tasks already complete)

**Comment by rub1e** [comment]
This was done at the end of the last tax year (obviously, or we'd be in trouble :fearful:), but I neglected to close it off.

New issue for this year is open [here](https://github.com/dwyl/hq/issues/549)
