### ISSUE TITLE
OKRs? CFRs? (The Key to Success Building Product!)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#520]
The slightly longer "_subtitle_" of this issue/story is: 

"_How to build a sustainable values-driven open source software product company in 3 months 
using a proven system to set company-wide, team & individual goals/tasks ("**Objectives**"), 
track metrics ("**Key Results**") and help each other to ship great UX that delights users_."
"_How are we going to encourage **Conversations**, **Feedback** and **Recognition** (CFRs) and 
ensure that we **celebrate** each milestone/win, and **share knowledge** and ["**unblock**"](https://github.com/dwyl/labels/issues/87) issues **swiftly**_.

# Story 📝 

As a "dwyler" I want to know _exactly_ what the goals of the company are 
and how my _personal_ objectives relate to achieving those goals
so that I can be focussed on my most important work and help my [fellows](https://en.wikipedia.org/wiki/Fellow) do the same.

# Context (_Why?_) 💭 

First a _brief_ history of @dwyl for anyone who isn't aware (_or people reading this in the future!_)

## History? 🔙 

We started @dwyl in Feb 2015 to build an App to help people _discover+do_ what they [_love_](https://youtu.be/lDfu8pA8tlo?t=30). 
We made our mission _reasonably_ clear in [https://github.com/dwyl/**start-here**](https://github.com/dwyl/start-here) which has been read by a few thousand people even though we haven't released our App yet! ⭐️ 
(_note: we don't see this as an "achievement", it's just an encouraging sign that people are interested_)

## Founders & Coders Mentoring/Directorship 🤓 

Early on we went on a  "_detour_" to help make Founders & Coders a sustainable _free+accessible_ technical training program in London https://www.foundersandcoders.com 
(_now expanding to other countries_) and helped empower hundreds of people with the skills they need to find work or create their own ideas!
(_**note**: we in no way take "credit" for the success of F&C. It's a massive team effort and there are many other people who deserve more "credit" than us. you know [who](https://github.com/orgs/foundersandcoders/people) you are!_ ❤️)

## "Mobile Web App Development Agency" 📱 

We spent 3 years building products/apps/services for _other_ people as an "agency". That was a good way to help the people on our team(s) gain some real-world dev/UX/PO experience and accumulate some bootstrap capital. Our clients are happy and all the products/projects we built are well-written, documented and maintainable (_except where Hapi.js has created a "moving target" with v.17 ..._ 🙄) 

## Agency != Product 🆗 |> 🦄 

The way we went about our work as an "agency" building web apps is _good_, as one of our team members recently remarked: "_our [**process**](https://github.com/dwyl/process-handbook) is **admired** by the wider **dev community**_". _However_, building apps for other people is _nothing_ like what it takes to build a successful software product. 

We know this because we've worked for both ***failed*** 📉⌛️💀  
and **_mega_ successful** 📈 startups (_and [read extensively](https://github.com/dwyl/home/tree/e2cf80da78de6120a3e2e19129568c399c598b39#library-of-creativitytechnologybusiness-focussed-books) on the subject of technology success/failure_) and  know _exactly_ what the `main` symptoms/predictors of both outcomes are. 
In the cases that lead to failure there is a lack of clarity/focus/purpose and people lose enthusiasm as the company crumbles from the *chaos*. Whereas a **_laser_ focused** company has the  **leadership**, clearly communicated vision/mission/goals that everyone in the team can _recite_ and there is a "team spirit" and sense of _urgency_ to the work, it gets done _fast_ and success is _possible_; not _guaranteed_ but _possible_.  

## Communication _Fail_...? 📣|> 🔇 

Historically we have not been very effective at _communicating_ the overall goal of our organisation/company/community ... this has lead to wasted effort, frustrated/confused people
and a lack of sense of direction, meaning or urgency. 😞 

I (_Nelson_) can hold my hand up and take ownership/responsibility for this failing. ✋ 
_However_, I would encourage others to _reflect_ on whether they have made the _effort_ to _proactively_ ask _questions_ when they are confused/stuck or whether they silently procrastinate on their FUD ... ❓ 

Everything can _easily_ be clarified if people are willing to ask questions. We have a culture that _welcomes_ questions of all kinds and we _celebrate_ the people who ask them because we _know_ that often others are thinking the same thing but have been conditioned by society that "not knowing the [right] answers" is "bad" and to "not look foolish" so they stay quiet ... 😞 

## We _Need_ to Get Better at Communicating! 💬 

We need to get _much_ better at communicating our vision/mission (_without sounding "grandiose"_).
Everyone needs to _re-formulate/remix_ @dwyl's vision/mission into their _own_ words to ensure they _understand_ what we are trying to achieve. 

> If anyone is not "on board" with the vision/mission or product, that's "OK", not everyone will be. 
We just need _everyone_ to be **100% honest** with each other on how they feel, and if anyone is not "feeling it" we are happy to help them find work with a different company/org that better matches their values and life goals. We have done this before, no hard feelings, everyone's still friends! Everyone who has moved on from working with @dwyl is doing something they love. To us that is a _resounding_ success. Unlike other most companies who only care about "employees" for as long as they are _extracting_ value from them, we continue caring and everyone is always welcome!
> Bottom line: ***speak up***! 

We need a **100% foolproof** way of formulating+recording our company/individual objectives & key results and _helping_ each other when someone is "stuck" ... 
Otherwise our company will crash-and-burn and we will all be dusting off our CV's. 

Each person in the @dwyl "core" team is _capable_ of working in a _much_ more focussed way.
We are _all_ able to be more targeted, learn faster, communicate more effectively and deliver better work in _less_ time. If your memory is "foggy" on when you were last _mega-effective_, that's a _sign_ that something needs to change. Our collective future _depends_ on it.

## _One Chance_ 🚀 

Not to sound overly _dramatic_ but we only get one shot at this. 
We need to ship a product that people _love_ using enough to [_pay_](https://github.com/nelsonic/nelsonic.github.io/issues/569) for. 

We have a _massive_ head start on other technology entrepreneurs in that we know what problem we want to solve, we have the skills we need to solve it and we have a _team_ of people who can _execute_. 

But we _also_ have a _major_ handicap: we are stuck in "good enough" mode from having PO's who were not [_demanding_](https://en.wikipedia.org/wiki/Pygmalion_effect) enough. We need to shake off the "good enough" mindset and go for _gold_! 🥇 
_Everything_ we do needs to be the _best_ of our ability. (_don't worry nobody will be "judged"...! Each person is responsible for determining what their own "**personal best**" is. Our only "judge" is the "end-user", if people **use** our product, pay for and share it with others, we know we're doing our best!_)

I hear you asking: "_How do I know what my **personal best** is...?_" 
With that in mind, we need a "_system_"! 
But first a few words on workplace "systems" ...

## We Have _Been_ Where You Are Now! 🤔 

Both Inês and I have _been_ where you are now. We have worked for small & large companies that either had no "system" or had a token "performance management" and "annual review" system that everybody thought was a pointless "chore" and treated as a "box-ticking exercise". 
We _know_ what a _bad_ system looks like and we have spent _years_ searching for a _good_ one.
We feel that the success of the companies using OKRs + CFRs as described in John Doerr's _superb_ book (_see below_) is worthy of our attention. We feel that [Larry Page](https://en.wikipedia.org/wiki/Larry_Page)'s endorsement:

## "_I wish I had this book nineteen years ago when we founded Google_" 

... is enough of a _reason_ to **`try`** the system. 

# Proposal (_What?_)💡 

We _propose_ the adoption of the OKR+CFR system used by Google, Amazon, Microsoft, Spotify, etc ...
To _maximise_ our chance of success while building our software product. 

## OKRs? 🎯+ 📊 

This management-speak sounding initialisation stands for "***Objectives & Key Results***". 
In a **nutshell**: OKRs are a way of defining company-wide (_and individual/personal_) **goals** (**Objectives**) that directly and clearly relate to the company's mission and the corresponding **metrics** (**Key Results**) that keep everyone accountable and "on track" (_or help each other to get "unstuck"!_)

> _Don't worry, I too was "**sceptical**" that a system this simple (_sounding_) could work ...
> But after reading the book I'm **convinced** that not only is it a **good `<option>`**, it's our **best one**_!

## CFRs 💬   +   👍/  👎   +   ❤️/🎉

CFRs (**Conversations**, **Feedback** and **Recognition**) is a short-hand for how to approach _humanising_ the system, encourage _teamwork_, communication (_even "hard truths_) and celebrate the efforts/success of each person in the team!

# Todo (_How?_) ✅ 

+ [ ] **_Everyone_** in the company should **read** "**_Measure_ What _Matters_**" by John Doerr https://www.amazon.com/Measure-What-Matters-Google-Foundation/dp/0525536221
For a _taste_, watch: https://sloanreview.mit.edu/video/john-doerr-on-okrs-and-measuring-what-matters/

> @dwyl will pay for your _personal_ copy of the book where you can make notes.
> Just tell us where you would like us to ship it! (_or if you prefer to read on eBook, let us know_) 

+ [ ] Once you have read the book, **please** leave a **comment** below so we can proceed to setting up the "system" with everyone giving their input (_even/especially anyone who is **sceptical**_). 

We _cannot_ move forward with this until/unless _everyone_ is on board with this.
We _must_ be _fanatically_ disciplined/focussed on what we are doing in the next few months/years.
We cannot afford to miss sprint milestones/deadlines or be "confused" as to what we _each_ of us needs to do. If you are _unsure_ of _anything_ open a question/issue _immediately_. 

+ [ ] If you have questions/reservations about having a "formal" goal setting, progress tracking and feedback giving mechanism, please _voice_ them either as comments below (_or if you prefer to do it "privately", speak to @iteles or @nelsonic_) 

Related to https://github.com/dwyl/hq/issues/145 How Can We Make @dwyl the _Best_ Company to work for?

**Comment by edwardcodes** [comment]
I really liked “the taste” of “Measure What Measures”, this is very serious and very straightforward.. the f.a.c.t.s (focus alignment commitment tracking and stretching) are every day with you and Inês 🚀 
I’m keen on adopting this system.

**Comment by iteles** [comment]
@nelsonic Thank you for making the time to open this issue which I should have opened a long time ago! I'm excited about where we're headed, it's been a long time coming.

> If anyone is not "on board" with the vision/mission or product, that's "OK", not everyone will be.
We just need everyone to be 100% honest with each other on how they feel...

This in particular hit home for me, I think this is where it starts. We need to be unafraid of having the tough conversations (which I *thought* I did well, but actually have been avoiding them my whole life and pretending with 'difficult' rather than the conversations that matter) and being viscerally honest with each other. 

I recently read [Radical Focus](https://smile.amazon.co.uk/Radical-Focus-Achieving-Important-Objectives/dp/0996006028/ref=as_li_ss_tl?ie=UTF8&qid=1548975095&sr=8-1&keywords=radical+focus&linkCode=sl1&tag=dwyl03-21&linkId=706c459b01104a416dd5125544f082c7&language=en_GB) and found it a really understandable beginner-level OKR book as well (it wasn't at all what I was expecting from the book) so I'll dig up my copy and provide some notes to complement everyone's comments on [Measure What Matters](https://smile.amazon.co.uk/Measure-What-Matters-Simple-Drives/dp/024134848X/ref=as_li_ss_tl?s=books&ie=UTF8&qid=1548975235&sr=1-1&keywords=measure+what+matters&linkCode=ll1&tag=dwyl03-21&linkId=c1478e6b926daaa1d7a6131691fbcb37&language=en_GB).

**Comment by SimonLab** [comment]
Just finished the first read of "Measures what matters".
The main idea of OKR in itself is quiet simple (create **objectives**, the what,  and key results, the how, to complete the objectives). The difficulty will be to apply the process to dwyl. We will have some tries/errors and a quick calibration phase. We need also to define the structure of our OKRs (time length: quarters seem to be mostly used in the book example but this seems to be a long period of time for dwyl, where do we write down our OKRs: in Github issues?, what is the description format of our OKR,... ) but I'm keen to start trying OKR and to write down our main objectives for the team.

Some main points and notes I wrote down:

p66: OKR scale: "OKR started with 14, 2 years later the team is 60"
p67: Create 3 to 4 personal objectives
p68: Introduce OKR process step by step instead of the full process in one go
p72: Doing too much too soon will end in pain (too much OKR process)
p83: Key results become obectives when passed down
p85: **Make key results time bounded and measurable**
p86: Avoid trickle down ojbectives:
  - loss of agility
  - lack of flexibility
  - marginalised contribution
  - no horizontal connections
p88: The higher the goal, the higher the performace; Let user set some of their own goal; Create a mixed of top-down and bottom up goals
**alignement: team working together to a common goal instead of not knowing what people are doing**
p128: "What can you be the best in the world" Jim Collins
p133 **BHAG: Big Hairy Audacious Goal**, setting big and aspirational goal improve performance
p138: "The gospel of 10x": aggressive goals
p147: "Get **uncomfortable excited**" by goals
p152: Allow user to make complex thing/action with a UX **phenomenally uncomplicated**
p160: The most important things need to be done first or they won't be done at all
p203: OKR force people to "think in the macro",  ie people are focus on the steps to achieve the main goal
p208: Create better conversations: talk about personal goals -> boost motivation and energy
p244: If all key results are in green (green, yellow, red for a result status) you failed, ie the OKR are not well defined
p245: Ideas are easy, execution is everything
p256: Poorly done/managed OKR are a waste of time. Well done OKR are a motivational management tool
Objectives are the **Whats**, Key Results are the ** Hows**

My next step is to read again the Google's OKR playbook and the resources (from p255) see how I can apply OKR to my own goals (on paper to start with), however it might be good to start to think how to apply it to dwyl too (might need some help for that).

**Comment by nelsonic** [comment]
Anyone interested in succeeding with OKRs should read:
+ https://en.wikipedia.org/wiki/Goodhart%27s_law (via: https://thehustle.co/Goodharts-Law )

**Comment by rub1e** [comment]
Apologies, I've finally ordered the book. This is all very exciting and inspirational! Will report back once I've made my way through it

As an aside, Goodhart's Law reminded me of this gem from Christopher Hitchens's crank younger brother, Peter:

![screenshot 2019-02-12 at 08 57 55](https://user-images.githubusercontent.com/11595920/52624257-4050d980-2ea6-11e9-97f0-7cdc1857a4c1.png)

**Comment by nelsonic** [comment]
OKRs from a development team’s perspective: 
https://zafulabs.com/2019/05/24/okrs-from-a-development-teams-perspective/
via: https://news.ycombinator.com/item?id=20004127

**Comment by nelsonic** [comment]
How to Set KPIs and Goals (Adora Cheung YC): https://youtu.be/lL6GdUHIBsM

**Comment by nelsonic** [comment]
Thoughts on OKRs: https://joeblu.com/blog/2022_05_okrs/
via: https://news.ycombinator.com/item?id=31422718
