### ISSUE TITLE
Zoom.us (Replace Google Hangouts/Meet) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#521]
# Story  ... 🤙 |> 😞 |> 💡 

As a product owner, team member or stakeholder
I want an _excellent_ way of running/attending & ***recording*** remote team meetings with _great_ quality
So that I can _communicate_ effectively with teammates and never _lose_ any insight.

_Additionally_ if/when I am _unable_ to attend the meeting,
I need a quick+easy way of catching up on the meeting by watching a _video_ (_double-speed!_)

# Context 💭 

We have been using Google Meet (_formerly "Hangouts"_) for the past 3 years to conduct all our remote meetings. It's been "OK" (_good but **not [great](https://en.wikipedia.org/wiki/Good_to_Great)**_) and @iteles captured our evaluation in #397 ...

Long story short: I (Nelson) am not "happy" with using Google Meet as I feel the product is an "MVP" that never got any "UX TLC", _advanced_ or "pro" features. I feel that if we are going to be a "remote first" company/org we need to _pay_ for a professional solution for our meetings. 

I _know_ that other people are "OK" with using G'Meet but we _cannot_ afford to have an "OK" tool.
Our tools need to be the _best_ for each task that we perform. As a remote team we need the _best_ communication tools so that we are never forced to compromise on our UX e.g: noisy/poor audio, delayed video (when presenting), squashed aspect ratio (when pair-programming), on-screen controls covering the text (when viewing a presentation), etc.

Not having a built-in way to record a product/client demo so that other stakeholders (_or not-present team members_) can play it back is a _real_ handicap that we need to address. 

> We (@jruts, @samhstn, @Danwhy, etc.) used Zoom.us at TC and it was _much_ better than G'Meet. 
> I feel that we should "level up" our tool(s) and this is the one I have experience with so that's why I'm suggesting it. I'm _very_ happy to hear alternative suggestions. (pls comment below!). 
**Note**: I/we am/are not _interested_ anything "free" or "cheaper", I/we want something "professional" and "high quality" and don't mind _paying_ for it because it's a "shovel" and we're digging for [gold!](https://medium.com/startup-grind/dont-mine-for-gold-when-you-can-sell-shovels-7ad6bc145542)

## “_Don't worry about the cost of a shovel when you’re digging for gold_”.

# Proposal 📝 

I propose that we _switch_ from using G'Meet to using https://Zoom.us/ 
because it is a single-product focussed company/app that does _one_ thing _really_ well. 

![image](https://user-images.githubusercontent.com/194400/52012061-88005a00-24d1-11e9-9612-7d21698372a6.png)
There is _zero_ ambiguity on their home page as to what they do. 

## Product: A _Dedicated_ Service/App for Meetings ✅ 

https://zoom.us/meetings
![image](https://user-images.githubusercontent.com/194400/52010490-92205980-24cd-11e9-845d-db7b3a6b0780.png)

## Pricing: €13.99/Month 💸 (_quite cheap really..._)

https://zoom.us/pricing
![image](https://user-images.githubusercontent.com/194400/52010395-571e2600-24cd-11e9-8e52-8980d5f0ba21.png)

## Pros ➕ 

+ **More professional**. our meeting link would always be the same. e.g: https://zoom.us/dwyl
    + if we _really_ want to get fancy (_later on when we are a **much** bigger org/company_) we can "_white-label_" the product and embed it into our App! 😮 https://developer.zoom.us/docs/api
+ **_Dedicated_ App** means no "hunting" around for the browser tab when we are trying to demo something and no annoying Meet controls covering the screen. 
+ **Higher quality video + audio** because the desktop app uses _much_ better codecs than G'Meet.
+ **_Built-in_ recording** functionality so _anyone_ running a meeting, demo, remote UX test, etc. can _easily_ record the session and it can be saved for later replay by people who were unable to attend.

## Cons ➖ 

+ **App** For best results, each person on the Meeting would need to download an App to their laptop/mobile. There is a "Web Client" that works reasonably well, but it has a "_limited feature set_".
see: https://support.zoom.us/hc/en-us/articles/214629443
The web client is perfect for our "Clients" who only want to attend the call and ask/answer questions but don't necessarily want/need any "advanced" functionality like keyboard shortcuts, live chat or the ability to _mute_ another attendee. 
+ Cost. €13.99/month (_I feel this is quite cheap when we consider the bump in quality/UX_ ...)
+ Privacy concerns? (_I'm obvs a "paranoid penguin" when it comes to privacy, but Zoom.us is a pretty respected App/company and I haven't heard any stories/rumours about a security/privacy weakness in their app/client or infrastructure ... does this warrant further investigation?_) 
+ Google Calendar integration? (_can we "survive" without this once everyone knows the link to our hangout which won't change ... also our App will allow people to set reminders..._) 

# _Short_ Term 📈 

In the short term we are going to start _recording_ our team meetings. 
In the same way that the IPFS team do. e.g: https://www.youtube.com/watch?v=hRAdkNnAnuU

> @alanshaw / @achingbrain / @olizilla can give us their _insight_ into how effective it is for **remote teams** to **_record_ meetings**. I _believe_ they are using Zoom.us (_please correct me otherwise gents_)

This will allow people who are _unable_ to attend a meeting (_for whatever reason e.g: dentist/doctor_)
to replay the meeting and "catch up" with what was discussed/shared/decided/agreed at _double speed_! 

It will _also_ add a level of _accountability_ to our meetings because "action items" will be _recorded_.

> **Note**: we will need to have a _rule_ that _everyone_ follows: that we do not "pick on" anyone for not "following through" with their verbal commitments given in meetings. Meetings are _not_ the place to make "_promises_". We will all be adopting written/published ["OKRs"](https://github.com/dwyl/hq/issues/520) where people will commit to achieving a _specific_ objective/goal. We will have a _clearly_ structured process for defining collective/individual goals ("**Objective**"), tracking progress ("**Key Results**") towards achieving them and requesting/offering _help_ when a goal/objective is proving more difficult/time-consuming than expected. see: https://github.com/dwyl/hq/issues/520

# _Longer_ Term 🎯 

Our goal has always been to have a _hypertransparent_ company/organisation. 
Longer term I expect us to allow the people _using_ our App to attend our weekly team meeting where we discuss the priorities and become a truly "open company" see: https://www.opencompany.org/about/

Our _Weekly_ Product (Time App) Demos are going to be recorded.
We will link to the recording in the _Weekly_ "release notes". Yes, 1-Week Sprints; we need to move _fast_!

Once we have some _momentum_ with our product we will **_invite_ key stakeholders** 
(_e.g: ["influencers"](https://youtu.be/jG7dSXcfVqE?t=133) in the personal effectiveness community e.g: Thomas Frank, Cal Newport, Tim Ferris, etc._) to attend our Weekly Demo Meetings and we will _present_ the feature that is _most_ relevant to them with mini _interview_ where we ask them for their "first thoughts & feedback". 
This content (video) will be re-packaged as the @dwyl weekly update podcast which the @dwyler _community_ will watch to be informed of the latest features in our App and learn from the "super achievers". 
It's a Tim Ferris Podcast meets Personal Effectiveness super-user podcast. 
Not really for "mass market" but for our "super fans". 
https://medium.com/swlh/how-to-make-something-people-love-a8364771b7e6

> Related to https://github.com/dwyl/hq/issues/397#issuecomment-336846920 where I noted that Google Meet doesn't have built-in "Record" feature.
> Also related to Gitter #517 which is a "free" tool that lacks features and has annoying bugs ... 
**Note**: Zoom.us will _not_ "_replace_" Gitter and we will not be using Zoom.us "instant messaging" outside of meetings, we still need to finalise our evaluation of Gitter before selecting our "chat" tool. I am only mentioning it here as we need to "upgrade" all our "remote-co-working tools"! 🛠 

# Todo ✅ 

+ [x] Everyone to Read through the https://zoom.us website features and see if there is anything I am missing ... any caveats? Terms+Conditions issues? Got any questions that are unanswered?

+ [x] Share your concerns/feelings on switching from G'Meet (_the Devil we know..._) 

+ [x] Share _suggestions_ for alternative tools if you have any! (_the only reason I'm proposing a new tool at the same time as I'm opening the issue for the "problem" is that I want to "fix" this ASAP!_)

# _Please_ Discuss! 💬 

Please add your thoughts/ideas/alternatives/concerns as comments below. 
We will be looking to _switch_ away from Google Meet as soon as Monday 4<sup>th</sup>.
So if you have _strong_ feelings about this, please don't sit on the fence; speak up!

Thanks! ✨

**Comment by SimonLab** [comment]
Very happy to try zoom, my only question was if they provide a client for linux, but they do!
![image](https://user-images.githubusercontent.com/6057298/52070248-4e365e80-2578-11e9-83bd-4d5b1dead82f.png)

https://zoom.us/download#client_4meeting

**Comment by iteles** [comment]
I have used Zoom once before, when I was having a call with some folks about a talk, in September 2017 so I'm out of date on how good it might be.
At the time, as a first time user, it made me jump through a lot of hoops to be able to use it and I had to install software on my computer (which, as a person on the receiving end of an invite, especially for a one-off call as was the case, I hate). I will check if this is still the case but if so, we could always use Zoom for our internal meetings and then test it with external folks and go from there.

Very happy to test this out, the recording feature alone is likely worth its weight in gold if it works well 🚀 

An **opt-*out** newsletter as part of signing up 😕: 
![image](https://user-images.githubusercontent.com/4185328/52115974-e4fe2c00-2607-11e9-9e90-9f0c06143035.png)

Doesn't allow me to try anything without going back to my email address for the activation link:
![image](https://user-images.githubusercontent.com/4185328/52118360-019d6280-260e-11e9-9757-23e8adde0820.png)

Sheesh, give me a second, I haven't even tried out the app yet, I can't go recommending it to other people!
![image](https://user-images.githubusercontent.com/4185328/52118467-4b864880-260e-11e9-9982-0bf48244fa13.png)

OK, looks like each person has a personal URL and it never changes. We're in!
![image](https://user-images.githubusercontent.com/4185328/52119098-f21f1900-260f-11e9-98e8-45640802546c.png)

Let's try this out and evaluate 👍

**Comment by nelsonic** [comment]
@iteles thanks for diving in. Do you feel that we can test Zoom.us for our CS Retro call _today_?

**Comment by iteles** [comment]
Already updated the invite 20 mins ago 👍

**Comment by nelsonic** [comment]
@iteles cool. 🎉 https://zoom.us/j/7014628618 (_for anyone reading this issue_)

Keyboard shortcuts: https://support.zoom.us/hc/en-us/articles/205683899-Hot-Keys-and-Keyboard-Shortcuts-for-Zoom

**Comment by nelsonic** [comment]
Native app means we get pop-over faces and can still look at content full-screen. 😮 
![image](https://user-images.githubusercontent.com/194400/52120987-049c5100-2616-11e9-9b9c-cb9539b8419d.png)

**Comment by RobStallion** [comment]
First impressions

I felt that zoom was pretty good. Other than the page not loading and having to get the app I felt it went pretty smoothly.

- The link in the calendar opens the app so it's pretty seamless to use.
- The keyboard shortcuts were clear and easy.
- The raise hand feature seems like a pretty good way to let people know you have something to say that isn't talking over someone or interrupting

**Comment by Danwhy** [comment]
I was quite happy with our trial. It seemed to handle all six of us with our videos displayed with no problems, which is more that can be said for Google Meet. 

Like Rob said, it was easy to connect. I like the desktop app as it means I don't have to go looking through my emails for the right hangout link. 

The biggest problem I've had with Meet is that my microphone doesn't work half the time when I connect to a call. It's too early to say whether using Zoom will fix that or if it's purely a problem on my end, but so far so good.

**Comment by SimonLab** [comment]
Our first call was good and without any issues (sound or video).
I like that the native app allow me to share all of my screens (couldn't do this with meet, and it was only working correctly with Chrome).
The video thumbnail is great too while reading/watching another screen.
So far so good

**Comment by nelsonic** [comment]
Can't join without @iteles ... 😕 
![image](https://user-images.githubusercontent.com/194400/52200146-d611b680-285f-11e9-9635-3c7f70c951fa.png)
We need to _pay_ for this service and all members of the "core" team should have host access.

**Comment by Cleop** [comment]
I feel like Zoom worked fine for our recent retrospective. I like the 'hand up' feature that @RobStallion came across. But like @iteles I was frustrated/confused by the initial set up journey and feel this could be confusing for clients.

**Comment by iteles** [comment]
Reporting back on **recordings** as I've been the only person to have access to these:
+ The recordings have worked well and have saved to my local machine:
![image](https://user-images.githubusercontent.com/4185328/52306677-8088f700-2990-11e9-9094-11755a8fc329.png)
+ Having these in Zoom starts at an extra €37/month
+ The only thing to note about these is that they do not show everyone on the call at once, only the person talking, even though when we are on the call itself we see everyone in the little side panel as @nelsonic noted here: https://github.com/dwyl/hq/issues/521#issuecomment-459695969
  + The only downside of this is that it's less of a 'team' event and more of one person speaking at any given time, but having a recording of this is much better than no recording!
+ The quality of the recordings is great, but of course very subject to the internet issues and lags of the host, so it's **imperative that the host has a good internet connection**!

**Comment by rub1e** [comment]
Just FYI - it's now possible to record G'Meetings - https://support.google.com/meet/answer/7557124?co=GENIE.Platform%3DDesktop&hl=en

(Yes, I know that doesn't solve any of the other issues!)

**Comment by olizilla** [comment]
It's the least worst solution I've used. It scales well (as long as
everyone is polite), we use it for all-hands calls with around 80 (mostly
muted) participants.

Recording calls has historically been pretty taxing on the host machine,
but only in as much as you will notice your fans spinning.

Linux + tiling window managers have had problems with screen sharing in the
past, but folks seem to have found configs that work now.

I mildly recommend it, but I also would use anything else right now.

O!

**Comment by iteles** [comment]
## Update _for now_
+ Zoom seems to be working well for our Club Soda standups and internal meetings (see comments above) and we can finally have at least 6 of us on video at the same time without it toppling over
+ Recording these standups in decent quality is *gold* 🏅
+ _Let's try it out_

> We'll make this our go-to standup tool for now and adjust as needed.

I have upgraded up to the paid plan (no 40 minute cut-off) and will **keep a close eye on which of the features we use**.

We can also test this with some benevolent external people like the Club Soda team and unless we have major issues, use it for our _increasingly fewer_ external calls 👍 

Account upgraded:
![image](https://user-images.githubusercontent.com/4185328/52331446-1dc74800-29f0-11e9-9e89-ef4b89b434ad.png)
![image](https://user-images.githubusercontent.com/4185328/52331504-43545180-29f0-11e9-94d0-956a0c8f979a.png)

What this _doesn't _ resolve is the problem @SimonLab mentioned above https://github.com/dwyl/hq/issues/521#issuecomment-460181058 of requiring one host so we ultimately need to pay for more hosts - let''s do this as needed.

**Comment by nelsonic** [comment]
@olizilla thanks for your feedback. ❤️ 
We _really_ value your experience with this as you are running/attending meetings with _lots_ of people and seeing _acceptable_ results. 
"least worst" and "Mildly recommend" ... are _ringing_ endorsements as far as I'm concerned. 😉 

"_least bad_" is the first step toward "_good_". 
I _agree_ that it's not "outstanding" by any means.  But it's **_objectively_ better** than Google Meet  which as sacrificed _call quality_ & scalability for UI simplicity. 

@rub1e thanks for the link to the Google Meet recording feature.
![image](https://user-images.githubusercontent.com/194400/52333687-ccba5280-29f5-11e9-93ac-27a6aa5bce77.png)
It's _good_ that it automatically saves the recording to Google Drive ... 🤔 
But Still don't think they have addressed the _quality_ issue(s) noted above. 
Having a recording of the meeting is _good_ but if the sound is patchy,
because the web-based codec isn't good, then it's of little use. 😞 

@iteles the recording only showing the speaker _must_ be a setting that can be changed.
All the IPFS/IPLD calls show the "all participants" view.
[![image](https://user-images.githubusercontent.com/194400/52333207-8d3f3680-29f4-11e9-8824-6c6499d4beed.png)](https://youtu.be/R8wIN9GWwOs?t=99)
https://youtu.be/R8wIN9GWwOs?t=99

> Note-to-self: **`default`** to smiling in team meetings when I'm _not_ talking ... 😊 

+ Recordings taking up lots of space is a "cost of business", we can afford more hard drives. 
(_we **already have** an **8TB NAS** for this exact purpose - video storage - ready to store the data..._)
+ I'm not interested in using the "**Zoom Cloud**", it's a _super_ over-priced addon that _could_ save someone time and we _could_ consider it if our _preferred_ option ends up being too time-consuming.
I would _prefer_ to have @edwardcodes take "ownership" for downloading, editing (_where necessary for security/privacy_), color-grading using an _automated_ workflow  (_to reduce the "washed out" effect of harsh lighting_) and uploading the video ***unlisted*** on YouTube. That way we get the full power of the YT bandwidth optimisation, player (speed) controls and built-in feedback mechanism.
+ The meeting host having a **good internet connection** will not be an issue once we have our bonded-pair of fiber-to-the-door connections; point **`#5`** in https://github.com/dwyl/home#why ...

@iteles given that there is no "security risk" in sharing the meeting host access with people in the "core" team, you can _share_ your Zoom.us login with me or @SimonLab without "fear".

We _definitely_ don't need to pay "£80 or £90 a month" for this tool. (_we only need **one** host account_)
And again, if the tool adds the _value_ by allowing us to be more effective with our work,
then it's _worth_ whatever we spend on it.
If I can invest 100 to **`make`** 200 I will do it _every_ time; it's like having a money printing machine! 💰 🌈

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/52401947-deb1f900-2aba-11e9-8c5f-3d582537e57f.png)
You see this error message when you enter a correct meeting ID but your host has not started the call yet. I feel like this is not a clear error message that could confuse a client and make them worry they're in the wrong place.

**Comment by iteles** [comment]
@Cleop Looks like it's not when the host isn't present but possibly because you can't just reuse a meeting ID, you have you schedule the meeting in Zoom first. Looking into it :+1:

**Comment by SimonLab** [comment]
It might be linked to https://github.com/dwyl/hq/issues/521#issuecomment-461437385 but this morning I couldn't start the meeting with the id we have been using so far (the one on the calendar notification). I'm not sure if I didn't set it up properly or if my zoom client didn't allow me to reuse the id of the previous meetings

**Comment by iteles** [comment]
@SimonLab Looks like you just can't reuse a meeting ID. I tried the meeting ID we used yesterday like you guys did and it didn't work for me either. 
Then just in  case it was a glitch from me changing the email address on the account, I tried the ID from the meeting you hosted this morning with that account and it also didn't work.

Looks like: meeting IDs are _one time usage_ unless you actually schedule a meeting within Zoom and then it knows that it can be reused.
I'll do that and then the next thing to test is whether this new ID can only be used for the exact time scheduled or other times.

**Comment by nelsonic** [comment]
Guys we are getting carried away with making _assumptions_ instead of actually asking the appropriate questions. Not only are meeting IDs re-usable we can define a human readable ID e.g: **/dwyl**. 
It's called a "Personal Meeting ID", please see: https://support.zoom.us/hc/en-us/articles/201362843-What-is-Personal-Meeting-ID-PMI-and-Personal-Link-

**Comment by iteles** [comment]
@nelsonic The human-readable URL ([vanity URL](https://support.zoom.us/hc/en-us/articles/215062646-Guidelines-for-Vanity-URL-Requests)) is reserved for the next level up of payment plan which requires a minimum of 10 hosts (i.e. £160 a month) 😉 On our plan though, we can define any  numeric value for the personal ID.

_More interestingly_, as you  were typing that, I was investigating and came across this little (at the time, unticked) box:
![image](https://user-images.githubusercontent.com/4185328/52422482-07071b00-2aee-11e9-935a-abbe2e865d89.png)

So it looks like this single URL _can_ be used 'on the fly', just not any old Zoom URL. Testing it for tomorrow!

**Comment by Cleop** [comment]
Yes this is the UI you see when the meeting hasn't started yet, as opposed to the invalid code error:
![image](https://user-images.githubusercontent.com/16775804/52469107-74648b80-2b82-11e9-80a2-2f118a9a5ed0.png)


This is more informative for clients.

**Comment by nelsonic** [comment]
~~clients~~ > Product 
(_we need this remote meeting tool to interact as a **software product** development team_)

**Comment by RobStallion** [comment]
I did a screen share with zoom yesterday and it made my laptop VERY hot (🔥) and I noticed that things started to run slightly slower than normal.

**Comment by nelsonic** [comment]
@RobStallion interesting. thanks for reporting your experience. 👍 

Have you ever tried to record your screen using QuickTime (_Mac Native recording App_) for that length of time? (_if your laptop did **not** overheat I would be very surprised..._) 🤔 

When I use Google Hangouts/Meet with QuickTime to record it _destroys_ the battery of my MacBook Air laptop in 20 mins (_which usually lasts ~3h doing "normal" work_) and overheats like an oven... 🍕

Interesting that you felt a _noticeable_ slowdown on your MBPr"15 ... 💭 
Were you using Atom and Chrome at the same time? Those tend to be process/RAM/power hungry too.

Generally speaking, when screen-capturing, unless you're recording a VR game dev session with lots of polygons to render, there isn't need for processor/GPU speed ... 



It would be _great_ if screen recording was not "taxing" on our machines, but sadly that's not the case.
This is less a "_fault_" of Zoom and more a "fact of life" unless you want to dive into "fan management" ...
https://photography.tutsplus.com/tutorials/help-how-to-fix-your-overheating-media-making-mac--cms-27335

Either way, good to keep an eye on. 
@iteles has been using her (_comparatively low-powered_) MacBook "12 to record Zoom calls
with _many_ other apps/tabs open; it would be good to get her feedback too. 💬

**Comment by RobStallion** [comment]
> Have you ever tried to record your screen using QuickTime (_Mac Native recording App_) for that length of time? (_if your laptop did **not** overheat I would be very surprised..._) 🤔

Once during FAC so I can't really say. I might check it out just to see what happens. I wasn't actually recording the screen though. I was just sharing (I don't know if this has the same effect but my guess would be it should be less taxing than sharing and recording).

> Interesting that you felt a _noticeable_ slowdown on your MBPr"15 ... 💭
Were you using Atom and Chrome at the same time? Those tend to be process/RAM/power hungry too.

Yes I was. I never had this happen when I was using hangouts but maybe it's to do with the fact that I used hangouts in chrome? One less 'hungry' thing running. (I just realised that I was also plugged into a 4k display which could also have been playing a role. Pushing more pixels is more taxing. (that being said I have done that on hangouts so idk what it is 🤷‍♂️)).

**Comment by iteles** [comment]
>  But typically I find video distracting. Often I’ll do a meeting where I have lots of people in case we need to get their input. But for most of the meeting I don’t need all of them to be paying attention (and I’m happy if they’re getting other work done). But if video is on, seeing people who are not paying attention just seems to viscerally kill the mood of almost any meeting.

From https://blog.stephenwolfram.com/2019/02/seeking-the-productive-life-some-details-of-my-personal-infrastructure/

I think the biggest issue here is the line: "I’ll do a meeting where I have lots of people in case we need to get their input" which I disagree with as a strategy entirely and kills the premise of this paragraph. 

But a good reminder that there are lots of different points of view on this!

**Comment by nelsonic** [comment]
I'm upgrading to the **_annual_ plan** (£119.90/year or £9.99/month) because I want to have meetings (_remote pairing mostly_) that last longer than 40 mins and don't give me a count-down that is visible in the video (_esp. if recording..._)
![image](https://user-images.githubusercontent.com/194400/56889543-8ca3c280-6a6e-11e9-80ad-45bfc87156f0.png)

£9.99/month might seem like a "lot" of money to pay for something that is "free" in Google Hangouts/Meet or Skype, etc. but as stated above: this is a business tool that I expect to use _every_ day. In the interest of not wasting _time_ with researching other "free" tools with _comparable_ features, I'm signing up to a _year_ of Zoom. 

If in the next 12 months anyone has a viable alternative suggestion, I'd be happy to consider it! 
(_please leave suggestions as comments in this thread_).

**Comment by nelsonic** [comment]
Closing issue for now. Got 12 months of Zoom. 🔍

**Comment by nelsonic** [comment]
Lame ... https://www.vice.com/en_us/article/k7e599/zoom-ios-app-sends-data-to-facebook-even-if-you-dont-have-a-facebook-account via https://news.ycombinator.com/item?id=22693792
