### ISSUE TITLE
FY18/19 Year End Accounts

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#525]
These are due at the end of December 2019 at both Companies House and HMRC.

BUT... why not go through this early? We've just been through this process for [FY17/18](#461) (including R&D #481), and we'll have to do a bit of finance work for the end of the tax year anyway (#515)

The first task here is to review what we have and make a list of tasks required!

@rub1e @iteles  Let's both add to the checklist below please ☑️ 

## Tasks
+ [x] Call with accountants on open questions left from FY17/18 #461  
+ [x] Make sure all of our invoicing to clients is up to date as of 30th April 2019
+ [x] Ensure all our outstanding expenses are paid by 30th April 2019
  + [x] Rent
  + [x] Pension contributions
  + [x] Reconcile all VAT-relevant transactions, complete VAT return and pay out 
  + [x] @iteles to make sure all of her expenses are in by the end of the financial year - and paid for 
  + [x] All dwylsummer expenses to be in by the end of the financial year - and paid for
  + [x] Confirm all dwyler invoices have been paid
  + [x] Run and pay payroll
+ [x] ** All *non-VAT*** reconciliations completed in Xero
+ [x] Payroll #515  
+ [x] Review Aged Payables & Aged Receivables reports to confirm these are correct
+ [x] Review balance sheet
+ [x] Review DLA
+ [x] Review P&L
+ [x] Submit accounts
+ [x] Prepare and submit capital expenditure form if relevant
+ [x] Submit CT600 corporation tax form
+ [x] Pay corporation tax

**Comment by iteles** [comment]
@rub1e As suggested, let's use the documentation you're creating from #406 to put together what we need and make sure it's up to  date and understandable 👍

**Comment by rub1e** [comment]
The annual accounts process is [already there](https://github.com/dwyl/process-handbook/blob/master/Finances/preparing-accounts-for-your-accountant.md) so what I'll do is use that list for FY18/19 and then fill in any gaps / update with any tips & tricks I've learned along the way

The last part of that documentation is the R&D process - that's ready but I need to check it over before submitting for review.

And really #515 should be done at the same time, so that's next

**Comment by iteles** [comment]
Filed & paid!
