### ISSUE TITLE
Email Tracking?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#536]
This morning we got this email which prominently displays the "Sender notified by Mailtrack" signature (_obviously translated to Portuguese because the sender is based in Brazil_):
![mail-track](https://user-images.githubusercontent.com/194400/58009290-01a26f00-7ae6-11e9-9563-c99c6fc504bf.png)

I can _understand_ why the sender wanted to have the Opening of their email tracked.
But I can't help but feel that tracking is an invasion of _my_ privacy and it made me want to _not_ reply to the email ...

I _did_ reply to the email because the sender appears to have made an effort hand-writing the email and I can empathise with the job-hunting saga having been there and sent _many_ emails and not received replies ...

![replied-to-job-request](https://user-images.githubusercontent.com/194400/58016448-8ba60400-7af5-11e9-933b-c22dfce03987.png)

> Side note: I think we need a "standard reply" for people who email us their CV ... 🤔 
> We get a lot of people emailing us about jobs and it would be good to point them 
to a specific page with a "_`before` you apply checklist_".

# Privacy? 

When people sign up to use the Mailtrack service, 
they give Mailtrack access to "manage" their email:

![image](https://user-images.githubusercontent.com/194400/58012060-82b03500-7aeb-11e9-8010-6e19865bfa60.png)

This means that Mailtrack has their fully address book and access to _all_ email. This means that anyone _using_ Mailtrack is "leaking" email addresses and content to a 3<sup>rd</sup> Party. I certainly did not authorise anyone to share my email address with a 3<sup>rd</sup> Party ...

## Notifications:

Notifications appear to include the recipients name:

![image](https://user-images.githubusercontent.com/194400/58012111-a4112100-7aeb-11e9-9dcc-ee741650fe8c.png)

This suggests that Mailtrack is storing the personal data in order to send the notification.
(_it's possible that they query Gmail's API to get the personal details of the recipient in order to send the Notification, but that is more effort and slower so probably not what they are doing..._)

## Chrome Extension?

When signing up to use Mailtrack you are prompted to install the Chrome Extension.
Using the extension, the sender using Mailtrack will have an extra column in their gmail 
indicating that the recipient opened the email, 
which when hovered over shows _when_ the email was (_supposedly_) opened.

![image](https://user-images.githubusercontent.com/194400/58011740-d53d2180-7aea-11e9-8367-0103427e3fba.png)

Most people don't think before installing extensions in Chrome ... 😞 
_Most_ Chrome extensions do not respect privacy and have access to the contents of _every_ web page the user accesses ...
![image](https://user-images.githubusercontent.com/194400/58016329-3a961000-7af5-11e9-9433-18853cac985a.png)
It continues to boggle my mind how much people trust random developers with ***all*** their data!

<br /><hr /><br />

## The Simplest _Highly Profitable_ SaaS App?

As side-note this product is _phenomenally_ simple! 
+ [ ] Gmail (Google Account) OAuth to request user permissions
  + [ ] Function to hoover up people's address books 🙄 
+ [ ] Gmail integration that inserts a signature with a tracking pixel/image.
+ [ ] Server that tracks the HTTP request for the image; effectively https://github.com/dwyl/hits
+ [ ] [Chrome Extension](https://chrome.google.com/webstore/detail/email-tracking-for-gmail/ndnaehgpjlnokgebbaldlmgkapkpjkkb) 
  + [ ] Extension Gmail integration for displaying open icon in inbox/sent mail
  + [ ] Notifications
+ [ ] Web UI showing a table of when email was opened
+ [ ] Payment processing
+ [ ] What `else`...?

The UX is _polished_ and that will have taken a decent amount of time.
But once the product is built there is _minimal_ maintenance and overhead,
so it's _highly_ profitable! 💰 

It's _obviously_ a service many people will pay good money for: https://mailtrack.io/en/pricing
![image](https://user-images.githubusercontent.com/194400/58009114-a2dcf580-7ae5-11e9-874a-ba8ae64920fc.png)
The Pro account is €4.99/month
![image](https://user-images.githubusercontent.com/194400/58014232-49c68f00-7af0-11e9-959f-d0fe9354701b.png)

<br /><hr /><br />

# Questions/Discussion

+ [ ] _When_ is it appropriate to use email tracking?
