### ISSUE TITLE
All monthly dwyl HQ expenses 

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#537]
As dwyl is metamorphosing, it would be good to have a run-down of our existing monthly expenses so that we can determine if the tools/services we are spending money on every month still serve us. 

## Tasks
+ [ ] List out monthly expenses
+ [ ] Ines to review these
+ [ ] Cancel expenses that no longer serve us
+ [ ] Reduce/increase expenditure for those that are serving us but not quite in the right way

**Comment by rub1e** [comment]
* Zoom - was monthly but we paid for a year in May
* Amazon Prime - £8
* Digital Risks (insurance)
* Linode hosting - used to be pennies, but now jumped up to £7-10 - so presumably that means it's actively being used?
* GSuite - we've cancelled all unused email addresses so it's only core usage
* Audible - £8
* Xero - payroll removed, so we're only paying for core + pay-as-you-go expenses module
* Heroku - $16 - as discussed, we're pretty sure this is the dwyl site
* 3 Mobile - varies - about a tenner
* GiffGaff - £20-30/m - not actually monthly but fairly regular

**Comment by iteles** [comment]
:+1: Perfect, thanks @rub1e ! Giffgaff was £12 til last month when the roaming ran out 🙄 
I'm on it!

**Comment by rub1e** [comment]
Sorry, meant to put WIP on there - there are a couple more I needed to add (have done now) - and will doublecheck I've caught everything tomorrow when I do #538

**Comment by iteles** [comment]
## Decisions being made

+ [x] Zoom - was monthly but we paid for a year in May **[Paid, decision to be reviewed in Apr-2020]**
+ [x] Amazon Prime - £8 **[cancelled, no longer needed]**
+ [x] Digital Risks (insurance) **[still required until we wrap up CS]**
+ [ ] Linode hosting - used to be pennies, but now jumped up to £22
+ [x] GSuite - we've cancelled all unused email addresses so it's only core usage
+ [x] Audible - £8
+ [x] Xero - payroll removed, so we're only paying for core + pay-as-you-go expenses module
+ [x] Heroku - $16 - dwyl site, required
+ [x] 3 Mobile - varies - about a tenner
+ [x] GiffGaff - Now barely in use, £10 every 2-3 months, to stay as-is
+ [x] Digital Ocean - $18
+ [ ] Clustered - £24

### Next Batch of Decisions/To be Reviewed
+ [ ] Zoom, should we renew annual subscription in May-2020
+ [x] Digital Risks (insurance), to be re-evaluated in 
+ [ ] Get data out of Xero and cancel May-2020
+ [x] Do we need all of our email addresses?

**Comment by rub1e** [comment]
Digital Risks - level of Professional Indemnity Insurance cover has been reduced, to reflect the fact that we're not working with as many clients as before so less cover is needed. This means a _significant_ saving on the monthly cost, while still providing more than sufficient cover. 

Latest documents saved in the insurance folder

**Comment by iteles** [comment]
Digital Ocean cancelled  by @nelsonic  👍

**Comment by nelsonic** [comment]
Working on cancelling the Clustered payment too.  Clustered is used for an email server ... 
So once I build a _severless_ email function https://github.com/dwyl/auth/issues/39 I can switch it off!
I transferred it to my own Monzo card a few months back 
so that I would feel the pain each month until it's switched off. 
After that I will also be looking at Linode https://github.com/dwyl/hits/issues/81
