### ISSUE TITLE
VAT Return | Aug to Oct 2019

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#539]
VAT Return for Q3 2019/20 - Aug to Oct

Deadline: 7th December 2019

## Tasks
+ [x] @iteles to update Co-op feed
+ [x] @iteles to check Santander feed
+ [x] @iteles to confirm all additional expenses are input (outside of bank expenses)
+ [x] @rub1e to review & reconcile all bank transactions
+ [x] @rub1e to run report
+ [x] @iteles to sense-check figures
+ [x] @rub1e to submit VAT return

**Comment by rub1e** [comment]
This is filed now, and they owe us a small sum. If there's anything that needs to be documented in terms of claiming it I'll do that, but hopefully they just credit our account and we don't need to do anything
