### ISSUE TITLE
VAT Return Nov to Jan 2020

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#543]
VAT Return for Q4 2019/20 - Nov 19 to Jan 20

Deadline: 7th March 2019

## Tasks
+ [x] @iteles to update Co-op feed
+ [x] @iteles to check Santander feed
+ [x] @iteles to confirm all additional expenses are input (outside of bank expenses)
+ [x] @rub1e to review & reconcile all bank transactions
+ [x] @rub1e to run report
+ [x] @iteles to sense-check figures
+ [x] @rub1e to submit VAT return

**Comment by iteles** [comment]
Assigning this to myself for initial actions and because we'll have VATable expenses to include in this quarter.

**Comment by iteles** [comment]
This was all done on time as per usual 👍
