### ISSUE TITLE
FY19/20 Accounts

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#551]
These are due at the end of December 2020 at both Companies House and HMRC.

## Tasks
+ [x] Make sure all of our invoicing is up to date as of 30th April 2020
+ [x] Ensure all our outstanding expenses are paid by 30th April 2020
  + [x] Rent
  + [ ] Reconcile all VAT-relevant transactions, complete VAT return and pay out 
  + [ ] @iteles to make sure all of her expenses are in by the end of the financial year - and paid for 
  + [x] All dwylsummer expenses to be in by the end of the financial year - and paid for
  + [x] Confirm all dwyler invoices have been paid
+ [x] **All *non-VAT*** reconciliations completed in Xero
+ [x] Review Transferwise payments have all been coded to the correct place
+ [x] End of tax year processes #549   
+ [x] Review Aged Payables & Aged Receivables reports to confirm these are correct
+ [x] Review balance sheet
+ [x] Review DLA
+ [x] Review P&L
+ [ ] Submit accounts
+ [x] Prepare and submit capital expenditure form if relevant
+ [x] Submit CT600 corporation tax form
+ [x] Pay corporation tax

**Comment by iteles** [comment]
Obviously this was done on time
