### ISSUE TITLE
Review VAT FY15/16 onwards

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#553]
Our VAT situation from the financial year beginning April 2017 onwards is a bit of a mess, both in terms of overpayments and because Xero was set up incorrectly.

Our accountants found and resolved a few issues last year whilst finalising the accounts but it transpired whilst finalising the FY18/19 accounts that all issues hadn't been accounted for.

**We are due money back from HMRC due to VAT overpayments** so we now need to fully review all our invoices and VAT payments from April 2017 onwards in order to pinpoint the exact quarters where discrepancies require reclaiming VAT.

## Tasks
+ [x] List all invoices, with VAT split out, invoice date and payment date
  + [x]  FY15/16
  + [x] FY16/17
  + [x] FY17/18
  + [x] FY18/19
  + [x] FY 19/20
+ [x] Review Xero against original spreadsheet
  + [x]  FY15/16
  + [x]  FY16/17
  + [x]  FY17/18
+ [x] Review and account for any discrepancies between Xero and original invoice spreadsheet
+ [x] Calculate correct VAT payments
+ [x] Review all VAT payments
  + [x]  FY15/16
  + [x] FY16/17
  + [x] FY17/18
  + [x] FY18/19
  + [x] FY 19/20
+ [x] Review all VAT returns
  + [x]  FY15/16
  + [x] FY16/17
  + [x] FY17/18
  + [x] FY18/19
  + [x] FY 19/20
+ [x] Find 2 VAT credits
  + [x] 1 from returns filed incorrectly in 2017 because Xero was set up incorrectly
  + [x] 1 from overpayments made in 2017 on VAT 
+ [x] Find discrepancies
  + [x]  FY15/16
  + [x] FY16/17
  + [x] FY17/18
  + [x] FY18/19
  + [x] FY 19/20
+ [x] Email figures to accountants
+ [x] Review figures with accountants
+ [x] File claims with HMRC

**Comment by iteles** [comment]
Note: We need to speak to the accountants about how this works for bad debt (unpaid invoices that we paid VAT on).

**Comment by iteles** [comment]
Additional VAT Returns no longer available in HMRC's online system have been requested by post on 1-Jul-2020 as this is the only way they can be obtained 🤦‍♀️

**Comment by iteles** [comment]
Had a call yesterday with new book keepers to finally pick this up again because the department we needed from our previous accountants didn't have availability for us and there were a number of other things we wanted to get sorted first (namely getting Xero to tally up properly).

Next task is to write up the conversation and email the summary to them.

Further should begin on this in 2 weeks, _to completion_, with a checkpoint after the first 10 hours of work.

**Comment by iteles** [comment]
Took a couple of hours to write everything out and make sure I had all relevant docs collated but I'm glad it's all together and in one place now 👍  Now we wait.

**Comment by iteles** [comment]
Our accountants have now finished reviewing this and are in the process of writing up the VAT claim 👍 

So far we've paid £390 (incl VAT) for the review and will pay another unspecified amount (time and materials) for the claims filing themselves.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/4185328/207923298-3c0eb44f-c95d-4bc4-9de9-1cab5f82b06f.png">

<img width="728" alt="image" src="https://user-images.githubusercontent.com/4185328/207922984-062fdd0a-74a6-4694-969e-4e222e131aea.png">

**Comment by iteles** [comment]
Done and filed. Now we wait to see if this is granted in this filing or if we have to file separately in our latest VAT return.

Payment for the filing of the claim (suspect we'll still pay for some follow-up time):
<img width="606" alt="image" src="https://user-images.githubusercontent.com/4185328/223586028-559619de-ba8f-464d-be33-dd6926f314a0.png">

**Comment by iteles** [comment]
Granted and paid.
