### ISSUE TITLE
VAT Return | 1 May to 30 July 2020

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#557]
VAT Return for Q1 2020/21 - May to July 2020

Deadline: 7th August 2020

## Tasks
+ [x] Update Co-op feed
+ [x] Check Santander feed
+ [x] Confirm all additional expenses are input (outside of bank expenses)
+ [x] Review & reconcile all bank transactions
+ [x] Run report
+ [x] Sense-check figures
+ [x] Submit VAT return

**Comment by iteles** [comment]
Note: To  be included are:
+ Electronics sent to our UK office
+ Raspberry Pi and components required for #556

**Comment by iteles** [comment]
This was all done and paid on time 👍
