### ISSUE TITLE
VAT Return | 1 August to 31 October 2020

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#560]
VAT Return for Q3 2020/21 - 1 August to 31 October 2020

Deadline: 7th November 2020

## Tasks
+ [x] Check Santander feed
+ [x] Confirm all additional expenses are input (outside of bank expenses)
+ [x] Review & reconcile all bank transactions
+ [x] Run report
+ [x] Sense-check figures
+ [x] Submit VAT return

**Comment by iteles** [comment]
This was completed and paid by direct debit.
