### ISSUE TITLE
VAT return | 1 November 2020 to 31st January 2021

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#561]
VAT Return for Q3 2020/21 - 1 November 2020 to 31st January 2021

Deadline: 7th March 2021

## Tasks
+ [ ] Check Santander feed
+ [ ] Confirm all additional expenses are input (outside of bank expenses)
+ [ ] Review & reconcile all bank transactions
+ [ ] Run report
+ [ ] Sense-check figures
+ [ ] Submit VAT return

**Comment by nelsonic** [comment]
New Apple Watch has a few quid of VAT. Can I forward the invoice to you?

**Comment by iteles** [comment]
Please do, anything like that (test device) which we need to reclaim VAT on, please forward invoices.
