### ISSUE TITLE
Professional Profile Photos 👤 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#567]
Some people have _really_ good online profile photos. 😍 
e.g. @sohilpandya took @iteles profile pic back in the Palmers Road days and it's stood the test of time. 📷 

Others have a random snap they took on their phone (_or worse, **`480p`** laptop web cam_) 10+ years ago ... 🙄 

This is such a no-brainer that I'm _kicking_ myself for not opening this issue sooner and getting it **`done`**!! 🤦‍♂️ 
It's not _urgent_ 🔥  but is definitely hight priority and would be good to get done ASAP. 🤞 

# Todo

+ [ ] **Research** how to do this ourselves using the equipment we have. 🔍 
+ [ ] Collect good examples of profile photos to gather requirements e.g. head position / camera angle.
+ [ ] Use highest quality camera we have e.g: https://github.com/dwyl/video/issues/49
  > Note: Using an iPhone is also an **`<option>`** provided we don't use any effects. 
  The portrait mode fuzzes the edges which might make it difficult to get consistent results for people with hair ... 👩 
  Hence suggesting using an _actual_ full frame camera [that we already have!] with GM lens. 💭 
+ [ ] Neutral (easily removed) background. 
+ [ ] Consistent quality **lighting**; a good opportunity to fix/document our lighting setup.
+ [ ] **Document** the _whole_ process start-to-finish so that:
  a. it can be replicated by us + others who want to elevate their profile photo game - even on a tight budget
  b. we can setup for new shots in as little time as possible (e.g. 2 mins)
  c. create appealing/useful/relevant content for a wider audience; great learning op!
+ [ ] Happy to be the test dummy on this as I _sorely_ need an update. (hence opening the issue...!)

@Stephanymtr if you don't mind leading this, please drop a comment. 🙏  (thanks!)
(obvs, you've already got a _superb_ profile pic cause you _get_ this, but for the rest of us ... 😉)

**Comment by Stephanymtr** [comment]
@nelsonic Your profile picture is a representation of Your Personal Brand. Let's do it! 

### ** Research how to do this ourselves using the equipment we have.**

I read through a couple of articles online. The tips most of them share when taking professional pictures are:

- **Choose a photo that looks like you.** Something that will reflect how you look on a daily basis at work.  

- **Clothing** Dressy or more formal clothing out-performed casual or artsy clothing in a [1991 study of students](https://journals.sagepub.com/doi/10.1177/0887302X9100900401). They were perceived to be more intelligent and given higher expectation of scholastic achievement. I mean, 1991 ⌛ ?!  I failed trying to find a more recent study, but I Stephany would say wearing what you would wear to work will represent you best. Given you work from home most days, try wearing clothes that match the dressiness of the company as a whole.

- **High resolution/quality photo** - We could use both your Sony camera as well as your iPhone. Although, I'm sure there are way more advantages in using a camera over a phone.

- **Framing** - We can obvs crop them later, but let's aim to have your face filling about 60% of the space.- 
![image](https://user-images.githubusercontent.com/91985721/176873989-ab600d53-8f42-473c-8799-2b25ea8ba061.png)
Present your [full-face to camera](https://journals.sagepub.com/doi/abs/10.1177/0301006620905216?journalCode=peca), as opposed to head turned away.  Making direct eye contact with the lens of the camera. It grabs people’s attention and helps for a connection.

- **No selfies** - duh...

- **SMILE** - if you consider your brand a little more serious, it’s okay to look serious. However, smiling can make you look more approachable and [increase attractiveness](https://onlinelibrary.wiley.com/doi/abs/10.1002/ejsp.2420200307).  [One study ](https://blog.photofeeler.com/perfect-photo/) ) of 800 profile pictures found that people view you as more likeable, competent, and influential when you smile. 

Genuine smile reference: 
![image](https://user-images.githubusercontent.com/91985721/176874163-df741307-b21b-4ba2-9fda-4116097b87d2.png)

- **No distracting backgrounds** - You have mentioned above: "Neutral (easily removed) background". I take you rather have your photo taken in front of a green screen ? 


During my research, I bumped into this app called [Photofreeler ](https://www.photofeeler.com/) multiple times (wonder why 💸 ). They help you select the best photos of yourself by removing self-bias. It does make sense to have other people (other than just yourself) picking out the best professional looking pictures. 
They also have a [blog](https://blog.photofeeler.com/how-to-take-a-professional-business-headshot-picture-by-yourself-at-home-free/) full of tips regarding this subject as well as online [photo editors] suggestion (https://blog.photofeeler.com/the-easiest-to-use-best-free-online-photo-editors/).

**Comment by Stephanymtr** [comment]
I must say I already have a go-to photo pose/setup that includes:
- smiling
- wearing business casual (ish)
- standing in front of a city/pretty background (that's not distracting)
I know it is not the most professional photo. However, that's the style I tend to learn towards as my main goal is to let my personality "shine through 🌟 " while displaying a positive and warm feeling. 
<img width="488" alt="Screenshot 2022-07-01 at 11 14 13" src="https://user-images.githubusercontent.com/91985721/176875845-ab3e0512-7587-4d0c-8aa2-1b7af4eca972.png">

**Comment by Stephanymtr** [comment]
### Collect good examples of profile photos

<img width="879" alt="Screenshot 2022-07-01 at 13 18 20" src="https://user-images.githubusercontent.com/91985721/176893343-a4963cb7-e139-46bd-9f46-156cb8763ef5.png">
<img width="876" alt="Screenshot 2022-07-01 at 13 17 17" src="https://user-images.githubusercontent.com/91985721/176893397-de722b4a-cb90-4c22-aa50-0ee91542c2eb.png">
<img width="877" alt="Screenshot 2022-07-01 at 13 16 42" src="https://user-images.githubusercontent.com/91985721/176893438-74c69c58-6152-4677-851c-49c8e6609eb0.png">
<img width="800" alt="Screenshot 2022-07-01 at 13 13 18" src="https://user-images.githubusercontent.com/91985721/176893508-f0bffc88-c559-416d-aef4-963b8c167f14.png">
<img width="800" alt="Screenshot 2022-07-01 at 13 12 33" src="https://user-images.githubusercontent.com/91985721/176893553-56182bab-3e09-4d07-8539-a29762e3dfd4.png">
<img width="880" alt="Screenshot 2022-07-01 at 13 19 11" src="https://user-images.githubusercontent.com/91985721/176893279-9694bf0f-19a6-4c0a-b80b-4264b00c437c.png">
<img width="876" alt="Screenshot 2022-07-01 at 13 18 51" src="https://user-images.githubusercontent.com/91985721/176893318-53b5665f-d436-484c-a57d-996bc7b5a15e.png">


I would like to know what kind of photo styles you are thinking of.

**Comment by nelsonic** [comment]
https://www.headshotpro.com/
via: https://news.ycombinator.com/item?id=35242174
