### ISSUE TITLE
DWYL FY21/22 accounts 

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#576]
These are due at the end of December 2020 at both Companies House and HMRC.

## Tasks
+ [x] Ensure all our outstanding expenses are paid by 30th April 2022
  + [x] Rent
  + [x] Reconcile all VAT-relevant transactions, complete VAT return and pay out 
  + [x] @iteles to make sure all of her expenses are in by the end of the financial year - and paid for 
  + [x] Confirm all dwyler invoices have been paid
+ [x] **All *non-VAT*** reconciliations completed in Xero
+ [x] End of tax year processes #549   
+ [x] Review Aged Payables & Aged Receivables reports to confirm these are correct
+ [x] Review balance sheet
+ [x] Review DLA
+ [x] Review P&L
+ [x] Submit accounts
+ [x] Prepare and submit capital expenditure form if relevant
+ [x] Submit CT600 corporation tax form
+ [x] Pay corporation tax

**Comment by iteles** [comment]
Completed and submitted on time.
