### ISSUE TITLE
Google Mail/Drive/Docs ("Workspace") Logo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#582]
https://admin.google.com/ac/companyprofile/personalization
![image](https://github.com/user-attachments/assets/64ccfee1-41b4-4704-9c83-2755beb7b122)

The image file should be in PNG or GIF format, up to 320 x 132 pixels and no bigger than 30KB. 

# Todo:

+ [ ] Prepare a version of the @dwyl logo #252 that conforms to these pixel dimensions. 🧑‍💻 👨‍🎨 
e.g: https://avatars.githubusercontent.com/u/11708465?s=132&v=4
+ [ ] Upload to `Google` Admin. ⬆️ 
+ [ ] Test that everything works. 🧪

**Comment by nelsonic** [comment]
Low priority because not many of us are using `Google Mail/Apps`.  
But would still be nice-to-have for the few of us that do use it ... 💭
